### ISSUE TITLE
Generated AAS in :urn/gen are xml instead of json

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-models#100]
Hi - currently, the generated AASs hold the xml-content in a .json-file. Couldn't find the action that generates these files at a first glance - it's probably just an issue in naming.

**Comment by jacewski-bosch** [comment]
@arnoweiss this probably belongs here: https://github.com/eclipse-tractusx/sldt-semantic-hub

**Comment by arnoweiss** [comment]
> @arnoweiss this probably belongs here: https://github.com/eclipse-tractusx/sldt-semantic-hub
Can you point me to the action that generates the */gen/ folders? We could then investigate where the error is (esmf-sdk or admin-shell-io could be other supects).

**Comment by jacewski-bosch** [comment]
no idea, really. my pointer was more of a general direction :) 
@tunacicek or @LuLeRoemer do you know where the AAS-xml is generated?

**Comment by LuLeRoemer** [comment]
@bs-jokri can you help here?

**Comment by bs-jokri** [comment]
btw.: the generation of the artifacts happens via 
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh

No GitHub action available so far.
