### ISSUE TITLE
[New Model]: Shared Aspect for BPNL/S/A

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sldt-semantic-models#105]
## Model Description
Issue, as discussed on 2023-03-13 during modelling session.
Several Models (e.g. EsrCertificate, SerialPartTypization#localIdentifiers#manufacturerId, much more) use at least one type of business partner number. There are three types: BNP Legal Entity (BPNL), BPN Site (BPNS), BPN Address (BPNA) representing an unique identifier within Catena-X to indentify a Partner on different levels.
The BPN Shared Aspect should show this relationship. From my understanding, there might be cases where I might allow either a bpns or bpnl to identify a partner. E.g., I as Fraunhofer ISST would be a site who could participate in business relationships on my own.  Same would apply to some sites of other partners. 

## Relevant Standards
- [EsrCertificate 1.0.1](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.esr_certificates.esr_certificate) has a regular Expression matching all BPN types (BPNL, BPNS, BPNA).
- [Catena-X Standard for BPNs](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_PDF_Maerz/5_BPDM/CX_-_0010_BUSINESS_PARTNER_NUMBER_PlatformCapabilityBPDM_v_1.0.1.pdf)

## Example Data
Following table might show some example scenarios. For examples of BPNL/S/A, please refer to the linked standards. The first case implies to be modelled as general "BPNL/S/A are specific BPN" (makes overall sense, if your case supports any type of BPN) or to be use case specific "BPN is _Either_ BPNL or BPNA" (that would then not be part of this aspect as it's very specific).
|Property| Value|
| ---- | ---- |
| Manufacturer Id | BPNL or BPNS (use case and partner dependent) |
| Manufacturered at site Id | BPNS |
| Deliver to address Id | BPNA |

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by arnoweiss** [comment]
will be solved with result of #103 . Concept agreed, modeling ongoing.

**Comment by bs-jokri** [comment]
resolved by 
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.shared.business_partner_number
