### ISSUE TITLE
[New Model]: OrderStatus

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sldt-semantic-models#113]
### Context
PURIS provides data as an operationalization of a DCM planning. You want to verify that the material needed for your production will be available on time. Therefore you commonly match the customer's demand against the supplier's production outputs. Also the customer's material stock (used to manufacture the products) matches the supplier's product stock (produced goods of the supplier).

### Actual Model
As these information are exchanged for an existing business relationship between two partner, we use the order (from Supplier and Customer side of view) as an "anchor point". The OrderStatus represents the **LATEST** status of the Order from **SUPPLIER** point of view. It has multiple positions that contains "AllocatedStocks". The AllocatedStock represents a quantity of a material, that has already been produced but not yet shipped.

## Relevant Standards
None

## Example Data
{
  "manufacturerOrderId": "M-Nbr-4711",
  "customerOrderId": "C-Nbr-4711",
  "orderPositionStatuses": [
    {
      "requiredDateOfCompletion": "2023-03",
      "manufacturerPartId": "123-0.740-3434-A",
      "customerSiteBpns": "BPNS1234567890YY",
      "allocatedStocks": [
        {
          "quantityOnAllocatedStock": {
            "quantityNumber": 2.5,
            "measurementUnit": "litre"
          },
          "manufacturerStockSiteBpns": "BPNS1234567890YY"
        }
      ],
      "positionId": "PositionId-01",
      "quantityOrdered": {
        "quantityNumber": 2.5,
        "measurementUnit": "litre"
      },
      "totalAllocatedQuantityOnStock": {
        "quantityNumber": 2.5,
        "measurementUnit": "litre"
      }
    }
  ]
}

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by arnoweiss** [comment]
Units of measure should be standardized[ in the aspect model](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/snapshot/units.html), not the payload.
