### ISSUE TITLE
[New Model]: Shared Model for Notification Header

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-tractusx/sldt-semantic-models#115]
## Model Description
While most models in Tractus-X are about data that is retrieved by consumers on-demand, there are also a lot of use cases where data is pushed to a data consumer by a push notification. To standardize the frame for these notifications, we are proposing a standardized header format for notifications, that can be used for domain or use-case-specific notifications as a shared aspect.

## Example Data
See model proposal: https://github.com/sschul33/sldt-semantic-models/blob/main/io.catenax.notification_header/1.0.0/NotificationHeader.ttl 

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by jacewski-bosch** [comment]
modeling_team

**Comment by arnoweiss** [comment]
see [CX-0023](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_PDF_Maerz/PLM_Quality_Use_Case_Traceability/CX_-_0023_Notification_API_v_1.1.1.pdf)
