### ISSUE TITLE
[Model Update]: PartAsSpecified

### ISSUE THREAD

**Issue by Kevinataccenture** [eclipse-tractusx/sldt-semantic-models#121]
## Update Reason
Similiar to BOMAsSpecified, we'd like to update the existing PartAsSpecified to add more usability / value to the model. As for now, the model is a digital twin without any reference point to the parts that are mentioned in the BOM. 
In order to change that, we would like to add the property "CatenaXId" in order to enable references from BOMAsSpecified.

By doing so, the Item Relationship Service can be integrated and use the parent-child relationship to depict a complete vehicle BOM.

DPP is one of the major use cases which will profit from an implementation together with the IRS.

Example Payload:
```

  {
  "partTypeInformation": {
    "ownerPartId": "5A1BA91",
    "nameAtOwner": "Steering Wheel",
    "itemCategory": "vehicle",
    "partDescription": "Steering wheel for vehicle"
    "partVersion": "05",
    "partClassification": [
      {
          "key": "BMW:PartFamily",
          "value": "STEEWHL"
      },
      {   
          "key": "STEP",
          "value": "steering wheel"
      },
    ],
  },
  "validityPeriod": {
    "validFrom": "2023-02-10T07:17:52.396Z",
    "validTo": "2023-02-10T07:17:52.396Z"
  },
  "catenaXId": "urn:uuid:580d3adf-1981-44a0-a214-13d6ceed9379",
  
    
  
}
```
[PartAsSpecified.zip](https://github.com/eclipse-tractusx/sldt-semantic-models/files/11273836/PartAsSpecified.zip)

[PartAsSpecified-payload_formatted_NEW_Model.txt](https://github.com/eclipse-tractusx/sldt-semantic-models/files/11087906/PartAsSpecified-payload_formatted_NEW_Model.txt)

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
Modeling_Team
