### ISSUE TITLE
[Model Update]: PCF 2.0.0 version

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#136]
## Update Reason
Update to BAMM 2.0.0.
(Bugs at the conversion have to be fixed. e.g contraints and the unit.)--> these are editor bugs.

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
talk to Steffen and sync on model changes. Maybe the update can be done with his model changes
