### ISSUE TITLE
Link in Model not working

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/sldt-semantic-models#139]
Within the Model Assembly Part Relationship, there is a link referenced to the openmanufacturingplatform which does not work. 

See https://github.com/eclipse-tractusx/sldt-semantic-models/blob/05faf19f6875cb321699249bb86f19591f60931f/io.catenax.assembly_part_relationship/1.1.1/AssemblyPartRelationship.ttl#L118

![image](https://user-images.githubusercontent.com/48311334/232476311-6bd595e7-e9b8-4085-be47-36e62d088bd7.png)

**Comment by jacewski-bosch** [comment]
fixed in #185 
@bs-jokri please close this issue
