### ISSUE TITLE
[Governance] BAMM and SAMM

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-models#155]
It's been a couple of months since the meta-model was renamed from bamm to samm. Yet, the old name is still present in all models. Have we made a conscious decision to keep it this way? Or should we discuss this as it will lead to ever-increasing confusion?

**Comment by chris-volk** [comment]
Hi @arnoweiss , I just found this issue, also FYI @bs-jokri  
I can see that this issue has been created in April. If you need help from us ESMF maintainers to discuss/proceed, please contact us (email  mailinglist https://accounts.eclipse.org/mailing-list/esmf-dev / forum https://www.eclipse.org/forums/index.php/f/617/ / github issue (for bugs/feature requests)

**Comment by bs-jokri** [comment]
Decision to make SAMM mandatory meta model from July, 7th onwards. Old BAMM models remain valid but need to be updated as soon as they are updated (incremental migration approach)
