### ISSUE TITLE
[Model Update]: Update description of field changedAt for DCM Use Case

### ISSUE THREAD

**Issue by nhaenis** [eclipse-tractusx/sldt-semantic-models#156]
## Update Reason
As part of a [user story](https://jira.catena-x.net/browse/ART4DCM-1873), the description of both of the DCM models are to be adapted in order to have a more precise definition for the interpretation of the field **_changedAt_**

Models to update:
[io.catenax.week_based_capacity_group](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.week_based_capacity_group)
[io.catenax.week_based_material_deman](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.week_based_material_demand)
New description texts:
> **WeekBasedMaterialDemand**

:changedAt a bamm:Property;
    bamm:description "Point in time when the content (any property according to the data model) of the material demand was changed, at the customer, either by a human user or an automated process."@en;

> **WeekBasedCapacityGroup**

:changedAt a bamm:Property;
    bamm:description "Point in time when the content (any property according to the data model) of the capacity group was changed, at the supplier, either by a human user or an automated process."@en;

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by nhaenis** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
will only be a patch release 1.0.1
