### ISSUE TITLE
[New Model]: Mandatory Dismantling

### ISSUE THREAD

**Issue by janinemuegge** [eclipse-tractusx/sldt-semantic-models#157]
## Model Description

With the Mandatory Dismantling data model, we want to mark the components in the vehicle with the notice for mandatory dismantling. 
Beschreibung hinzufügen

## Relevant Standards

Altfahrzeugverordnung 2000/53 EG (vehicle level)

## Example Data

Screenshot Excel

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by bs-jokri** [comment]
@janinemuegge is this model request still required? If not, could you close? (If it is required in the future we can reopen or create a new issue)

**Comment by janinemuegge** [comment]
Yes, this is still relevant. However, it must be adapted to the new legislation. Benjamin Mielke (BMW) and me will prepare a first proposal.

**Comment by jSchuetz88** [comment]
I think by now we can close it. As version 1 of the model has been published a while ago. And currently version 2.0 is under review.
