### ISSUE TITLE
[Model Update]: CX-0040 PartsAnalyses to V2.0.0

### ISSUE THREAD

**Issue by TorstenHirsch** [eclipse-tractusx/sldt-semantic-models#162]
## Update Reason
During mapping of test data the use case QAX team figured out that some attributes/properties were missing.
Therefore we would like to add the missing attributes. In addition there were 2 attributes that were named inconsistently and we would like to migrate to SAMM 2.0. --> Both will lead to a new major version 2.0.0 of the model

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders: Discussed with QAX members
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.parts_analyses/1.0.0
