### ISSUE TITLE
[New Model]: List of CX - 0037 Semantic Model Vehicle Product Discription needed for QAX

### ISSUE THREAD

**Issue by TorstenHirsch** [eclipse-tractusx/sldt-semantic-models#163]
## Model Description
The CX standard CX-0037 Vehicle.ProductDescription allows to transfer the data of ONE vehicle.
Request from QAX members: Allow to transfer a list of Vehicle.ProductDescription
Idea for solving the request: Keep standard CX-0037 Vehicle.ProductDescription as it is and built a new model with a list of it and refer the model CX-0037 Vehicle.ProductDescription

## Relevant Standards
CX-0037 Vehicle.ProductDescription

## Example Data

ListOfVehicles - listOfVehicles - ProductDescription

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case: Use case QAX (Quality)
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by bs-jokri** [comment]
will reference the existing model 
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.vehicle.product_description/2.0.0/ProductDescription.ttl
and will reference not only one but several vehicles
