### ISSUE TITLE
[Model Update]: MaterialforRecycling

### ISSUE THREAD

**Issue by ChristopherWinterZF** [eclipse-tractusx/sldt-semantic-models#168]
## Update Reason
Material content (inkl. recycled material) in the products.

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by catroest** [comment]
@bs-jokri redundant with #261 and the corresponding PR. Can be deleted
