### ISSUE TITLE
[Model Update]:  Updating io.catenax.vehicle.product_description to version 3.0.0

### ISSUE THREAD

**Issue by TorstenHirsch** [eclipse-tractusx/sldt-semantic-models#176]
## Update Reason
The issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/163 
uses as external reference io.catenax.vehicle.product_description 
The new model of  issue 163 already uses SAMM 2.0.0 as language. Unfortunately I cannot reference a model written in bamm:2.0.0 in a modell written in samm:2.0.0.

Therefore:
- Request is to upgrade existing model io.catenax.vehicle.product_description:2.0.0(bamm:2.0.0) to io.catenax.vehicle.product_description:3.0.0 (written in samm:2.0.0)

Proposal:
Use case quality (QAX) is switching to io.catenax.vehicle.product_description:3.0.0
All other use cases can stay with io.catenax.vehicle.product_description:2.0.0

## MS1 Criteria
- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
fixed by https://github.com/eclipse-tractusx/sldt-semantic-models/pull/178
