### ISSUE TITLE
[New Model]: UserEstimatedLoading

### ISSUE THREAD

**Issue by JuttaRoh** [eclipse-tractusx/sldt-semantic-models#179]
## Model Description

The use case EnduranceEstimator aims to estimate the remaining usefule life of a vehicle respectively a vehicle component using only basic vehicle data and usage description. Usage description comprises information on driver, economic or sportive style; application, city or long distance motorway driving, or trailer use; and typogaphy regarding hilliness and curviness.
This model standarize the input in order to have a defined numerical description of usage description and to define the basis vehicle paramater.

## Relevant Standards

Hilliness/Curviness -> see VMC - VirtualMeasurementCampaign, ITWM
Classification for driver style: → see WLTC

## Example Data

The payload for the EnduranceEstimator is devided in 

vehicle status
static vehicle parameter
usage profiles
future usage 
Static vehicle data are power, weight, and drivetrain information.
Profiles contain driver style, and usage like city driving or trailer use.

example json:

{
    "vehiclestatus": {
        "milage": 10000                        // the total milage of the vehicle in km
    },
    "vehicle": {                                                  //  aspect model vehicle.product.description contains some, but not all properties   
        "hsn": "0005",                                         // manufactures code number (Herstellerschlüsselnummer)
        "tsn": "DDV",                                          // type code number (Typschlüsselnummer) 
        "grossVehicleWeightKG": 1998,              // mass of the vehicle in kg  // KBA: TECHZULGESAMTMASSE
        "nominalPowerKW": 300,                       // the power of the vehicle in kW  //  KBA: NENNLEISTKW_4        // productDescription:  engine-power-EnginePower
        "codeTransmission": "automatic",          // the type of gearbox, // KBA: CODE_GETRTYP
        "energySource": "petrol hybrid",            //  KBA: CODE_KRAFTSTOFF                                                          //  productDescription:  fuel       
        "engineCapacityCCM": 4350,                 // KBA: HUBRAUM                                                                          // productDescription:  engine-size-CubicCapacity
        "numberOfPoweredAxles": 2                  // the number of drive axles // KBA: ANTRIEBSACHS
    },
    "history": [                              // list of history scenarios
        {
            "percentage": 28,                   // the percentage of this driving profile of the total milage
            "drivingStyle": 20,                  // 1-100, 1 = very careful, 100 = very sporty
            "hilliness": 30,                        // 1-100, 1 = flat, 100 = very hilly, default 20
            "curviness": 50,                      // 1-100, 1 = straight, 100 = very curvy, default 20
            "trailerUse": true,                   // is a trailer used?
            "cityDriving": false ,               // does the majority of this driving profile take place in cities?
            "longDistance" : false            // long distance driving, usage of motorway
        },
        {
            "percentage": 36,
            "style": 80,
            "hilliness": 80,
            "curviness": 60,
            "trailer_use": false,
            "cityDriving": false
        },
        {
            "percentage": 36,
            "style": 20,
            "hilliness": 10,
            "curviness": 20,
            "trailer_use": false,
            "cityDriving": true
        }
    ],
    "future": [                                    //  future scenario
            {
                "percentage": 10,
                "style": 100,
                "hilliness": 75,
                "curviness": 75,
                "trailer_use": 0,
                "cityDriving": false
            },
            {
                "percentage": 40,
                "style": 4,
                "hilliness": 20,
                "trailer_use": 0,
                "cityDriving": true
            },
            {
                "percentage": 50,
                "style": 20,
                "hilliness": 72,
                "trailer_use": 0,
                "cityDriving": false
            }
        ]
}

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by JuttaRoh** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
IDea: check if adjustment to vehicle.ProductDescription would help to increase reusability of model elements among models

**Comment by bs-jokri** [comment]
closed by https://github.com/eclipse-tractusx/sldt-semantic-models/pull/199
