### ISSUE TITLE
[Model Update]: Sealant Pass in correspondence with Digital Product Pass

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#193]
## Update Reason
Update of: https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.sealant.sealant_pass
to fit with the: https://github.com/eclipse-tractusx/sldt-semantic-models/issues/183 new Digital Product Passport

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by catroest** [comment]
modeling_team

**Comment by bs-jokri** [comment]
Migration Strategy: Both models (and the applications, which use those models) will be actively used for a while in parallel. Further details will be developed.

**Comment by bs-jokri** [comment]
@catroest what are the plans here? Will there be a model update soon?

**Comment by catroest** [comment]
@bs-jokri this topic was pushed back and will be reopened later
