### ISSUE TITLE
[Model Update]: SingleLevelUsageAsBuilt: prepare for Decentralized Digital Twin Registry

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-tractusx/sldt-semantic-models#196]
## Update Reason
In order to support efficient data chain building in a environment with a decentralized digital twin registry, the identifier of a business Partner who owns a referenced Digital Twin must be included in the reference. 

## Sample Data

See updated model: 
#198 

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by jacewski-bosch** [comment]
modeling_team

**Comment by bs-jokri** [comment]
will be a major update as it introduces a mandatory new property.
