### ISSUE TITLE
[Model Update]: add life cycle "Standardized" to standardized aspect models

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-tractusx/sldt-semantic-models#22]
## Update Reason
Catena-X standardized several aspect models: https://catena-x.net/de/standard-library
namely SUS-002, TRA-001, TRA-002 and TRA-003.
We discussed and decided that for this purpose a life cycle "standard" or "standardized" shall be used according to the governance process 

I.e. update https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.pcf/2.0.0/metadata.json

{ "status" : "release"} ==> { "status" : "standard"}

a.s.o.

If not yet supported for syncronization with Semantic Hub first introduce new life cycle in semantic Hub.

**Comment by bs-jokri** [comment]
semantic hub is updated
new template for status change introduced https://github.com/eclipse-tractusx/sldt-semantic-models/pull/210
