### ISSUE TITLE
[New Model]: DigitalPassport

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#222]
## Model Description
Rename and relocate the digital product passport to:
<urn:bamm:io.catenax.generic.digital_product_passport:1.0.0#DigitalProductPassport>

Reason:
Conformity to future passport models e.g:
<urn:bamm:io.catenax.battery.digital_product_passport:1.0.0#DigitalProductPassport> or <urn:bamm:io.catenax.transmission.digital_product_passport:1.0.0#DigitalProductPassport>

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by catroest** [comment]
modeling_team

**Comment by bs-jokri** [comment]
ticket is about renaming the namespace from
@prefix : <urn:bamm:io.catenax.digital_product_passport:1.0.0#>.
to
@prefix : <urn:bamm:io.catenax.generic.digital_product_passport:1.0.0#>.


reason is that this model represents the generic structure, which will then be used in specific models for specific products types (battery, vehicle, transmission)

As this is only a renaming of the namespace and all the other models of the modeling effort are already prepared, this model will still stay as BAMM model and be migration for Release 3.2.

**Comment by bs-jokri** [comment]
#223 is the corresponding  model deprecation request to deprecate this model with the old namespace
