### ISSUE TITLE
[New Model]: ShopfloorInformationService: SISRequestOperations

### ISSUE THREAD

**Issue by wehrstedt-jan** [eclipse-tractusx/sldt-semantic-models#229]
## Model Description
The shopfloor information results contains the forecasting information exchanged between the Modular Production and a second party (customer, logistical etc.).
The forecasting information gives an overview about the current processing state of a product and the estimated production date.
This information will be exchanged between the partners either on request, cyclic with a fixed cycle or on notification, if a forecast is changing.

## Example Data
SMC|Property | mand./opt. | Semantic ID | Remark
--|-- | -- | -- | --
||CX_PartnerID|	mandatory| string |	could be the same as BPN
||CustomerID|	mandatory|	string | internal customer ID
||OrderID|	mandatory|	string| 
||CommunicationMode|	mandatory|	enum (synchronous, cyclic, notification)|	
||Interval|	opt|	TimeValue [enumTimeUnits, uint ]	|required for "cyclic" mode
||Deviation|	opt|	TimeValue [enumTimeUnits, uint ]| if not defined, a default value willl be used. Depending on the data provider actual deviation can be larger, as a lower bound is given by the data provider
||Precision|	opt|	TimeValue [enumTimeUnits, uint ]| 	if not defined, a default value willl be used. Depending on the data provider actual deviation can be larger, as a lower bound is given by the data provider

## MS1 Criteria (MS1 was done in Ticket 180: https://github.com/eclipse-tractusx/sldt-semantic-models/issues/180)

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by wehrstedt-jan** [comment]
modeling_team

**Comment by wehrstedt-jan** [comment]
accidently closed

**Comment by bs-jokri** [comment]
replaces #180 to track the models separately.
