### ISSUE TITLE
[Model Deprecation]: PartAsPlanned 1.0.0 Deprecate PartAsPlanned 1.0.1 Release

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#251]
## Update Reason
PR was for PartAsPlanned V1.0.1 instead of 1.0.0, this PR will correct the mistake. 

## MS1 Criteria

- [ ] The model that should be deprecated exists and is not deprecated already
- [ ] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by jonbckr** [comment]
modeling_team

**Comment by bosserf** [comment]
The model that should be deprecated exists and is not deprecated already -> OK
 The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect) -> OK
 A shared aspect, which will be deprecated, is not used by any released aspect model -> OK

**Comment by bosserf** [comment]
MS1 approved by group
