### ISSUE TITLE
[New Model] .shopfloor_information_type

### ISSUE THREAD

**Issue by wehrstedt-jan** [eclipse-tractusx/sldt-semantic-models#253]
## Model Description
The shopfloor information results contains the forecasting information exchanged between the Modular Production and a second party (customer, logistical etc.).
The forecasting information gives an overview about the current processing state of a product and the estimated production date.
This information will be exchanged between the partners either on request, cyclic with a fixed cycle or on notification, if a forecast is changing.

for https://github.com/eclipse-tractusx/sldt-semantic-models/issues/230 and https://github.com/eclipse-tractusx/sldt-semantic-models/issues/231 common data will be outsorurced into this model 

## Example Data
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "Collection of types used in multiple data models of the Shopfloor Information Service",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum" : {
        "type" : "string",
        "description" : "Enumerates all possible communication modes",
        "enum" : [ "synchronous", "cyclic", "notification" ]
      },
      "urn_samm_io.catenax.messaging_header_1.0.0_VersionCharacteristic" : {
        "type" : "string",
        "description" : "Characteristic defining the value of version."
      },
      "urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum" : {
        "type" : "string",
        "description" : "Enumerates all possible time units",
        "enum" : [ "Month", "Day", "Week", "Hour", "Minute", "Second" ]
      },
      "urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic" : {
        "type" : "number",
        "description" : "The value of the specified timeUnit as an integer value"
      },
      "urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeValueCharacteristic" : {
        "description" : "Link to the  TimeUnit Data Type",
        "type" : "object",
        "properties" : {
          "timeUnit" : {
            "description" : "Specifies the unit in which the time is represented",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum"
          },
          "value" : {
            "description" : "The amount of timeUnits considered",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic"
          }
        },
        "required" : [ "timeUnit", "value" ]
      }
    }
  },
  "properties" : {
    "communicationMode" : {
      "description" : "Specification of the communication mode",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum"
    },
    "versionDataModel" : {
      "description" : "Specifies the used version of the data model",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.messaging_header_1.0.0_VersionCharacteristic"
    },
    "timeValue" : {
      "description" : "A time Value property",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeValueCharacteristic"
    }
  },
  "required" : [ "communicationMode", "versionDataModel", "timeValue" ]
}

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by wehrstedt-jan** [comment]
modeling_team

**Comment by bosserf** [comment]
The proposed aspect model does not exist already -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> OK
 The proposal references a Catena-X use case -> OK
 Relevant standards are mentioned/linked -> OK /not applicable
 A first draft of the data structure is provided in an example -> OK

**Comment by bosserf** [comment]
MS1 approved  by group

**Comment by bs-jokri** [comment]
pr merged can be closed.
