### ISSUE TITLE
[Model Update]: essincident

### ISSUE THREAD

**Issue by birgitZF** [eclipse-tractusx/sldt-semantic-models#255]
## Update Reason
Major release required for our data model: New fields, re-name of fields, delete fields
All changes discussed within our use case team and our implementation partner

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
Modeling_Team

**Comment by bosserf** [comment]
MS1 approved by the group -> work can be continued
