### ISSUE TITLE
[Model Update]: Digital Product Passport 2.0.0

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#260]
## Update Reason
Update the model Digital Product Passport to version 2.0.0. This version will be standardized and used as a "final" version in the application. Version 1.0.0 will be used in the application in a transition phase.

Changes: 
- update almost all attribute description to reference the ESPR
- change structure how to add optional document sources
- add new attributes which were missing from the regulation
- fewer shared aspects used, because they don't fit the need (physicalDimensions: no possibility to choose units; SerialPart: no possibility to add models (model - batch - part); PCF: in clarification)

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by catroest** [comment]
modeling team

**Comment by jacewski-bosch** [comment]
The model that should be updated exists -> OK
 The referenced use case exists -> OK
 The potential updates are discussed with all stakeholders -> OK
 A decision on versioning was made in consensus with the affected parties [according to the guidelines] (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning). ->OK
 The potential update will be either
 backward compatible or
 a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed -> OK

MS1 approval given by group
