### ISSUE TITLE
[Model Update]: Material For Recycling

### ISSUE THREAD

**Issue by sabinewichmann** [eclipse-tractusx/sldt-semantic-models#261]
## Update Reason
 Current data model is insufficient because it doesn't describe general material properties and detailed secondary material content properties. The updated model consolidates input from Material for Homologation, Material for Recycling and Secondary Material Content and proposes one data model. 
-> Current existing data model: Material for recycling
--> use case Circular Economy, Circularity Kit - Secondary Material Content Feature 
--> model update has been discussed with all relevant stakeholders 
## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bosserf** [comment]
MS1 approval agreed upon by team

**Comment by sabinewichmann** [comment]
@bosserf we would like to request the M2 approval for the model

**Comment by bosserf** [comment]
@sabinewichmann thanks for the request which I now forward to @bs-jokri, who is back and will take over
