### ISSUE TITLE
[New Model]: Common Material Demand Model

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sldt-semantic-models#262]
## Model Description
In PURIS, we want to exchange information so that partners (supplier & customer) do increase supply assurance. Therefore we would like to enhance the [WeekBasedMaterialDemand](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.week_based_material_demand/1.0.1) model to allow daily demands and use this model to allow a customer to share demands derived from the actual production plan (Note: NOT orders).

We're currently working with DCM on how to get a common view on the model.

New features needed:
- introduction of demand rate to distinguish demands per day and per calendar week.
- probably refine semantics to have a differentiation in the planning and actual context.

## Relevant Standards
CX-0047

## Example Data
``` json
{
  "unitOfMeasure": "GRM",
  "materialDescriptionCustomer": "Spark Plug",
  "materialDemandId": "0157ba42-d2a8-4e28-8565-7b07830c1110",
  "materialNumberSupplier": "MNR-8101-ID146955.001",
  "supplier": "BPNL6666666666YY",
  "changedAt": "2023-03-10T12:27:11.320Z",
  "materialNumberCatenaX": "urn:uuid:48878d48-6f1d-47f5-8ded-a441d0d879df",
  "demandSeries": [
    {
      "expectedSupplierLocation": "BPNS8888888888XX",
      "demands": [
        {
          "demand": 1,
          "pointInTime": "2023-07-21T09:42:22.034-07:00",
          "demandRate": {
            "demandRateCode": "cw"
          }
        }
      ],
      "customerLocation": "BPNS8888888888XX",
      "demandCategory": {
        "demandCategoryCode": "0001"
      }
    }
  ],
  "materialNumberCustomer": "MNR-7307-AU340474.002",
  "customer": "BPNL8888888888XX"
}
```

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by tom-rm-meyer-ISST** [comment]
modeling_team

**Comment by bosserf** [comment]
MS1 Criteria
 The proposed aspect model does not exist already -> new name, not new version -> new model -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> follow up discussion needed with DCM
 The proposal references a Catena-X use case -> DCM&PURIS
 Relevant standards are mentioned/linked -> DCM Standard listed; no external standard identified 
 A first draft of the data structure is provided in an example -> OK

MS1 approval will be given by Team, but further Discussion with DCM needed : model update or different model
