### ISSUE TITLE
[Model Update]: update shared aspect address from BAMM to SAMM 

### ISSUE THREAD

**Issue by birgitZF** [eclipse-tractusx/sldt-semantic-models#264]
## Update Reason

the shared aspect address 2.0.0 needs to be updated to SAMM because whenever it is referenced by other models that are in SAMM, validation of the other model fails

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by agg3fe** [comment]
The model that should be updated exists -> OK
 The referenced use case exists -> OK
 The potential updates are discussed with all stakeholders -> OK
 A decision on versioning was made in consensus with the affected parties [according to the guidelines] -> OK
(https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
 The potential update will be either
 backward compatible or
 a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed -> It is going to be a new version converted from 2.0.0 (BAMM) to 3.0.0 (SAMM)

**Comment by agg3fe** [comment]
MS1 Approval Provided

**Comment by bs-jokri** [comment]
resolved by https://github.com/eclipse-tractusx/sldt-semantic-models/pull/267
