### ISSUE TITLE
[Model Standardization]: BatteryPass 3.0.0

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#272]
## Link to Standards Document
https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_PDF_Maerz/Sustainability_Use_Case_Circular_Economy/CX_-_0034_Data_Model_BatteryPass_UseCase_CE_v_1.0.1.pdf

## MS1 Criteria

- [x] The model exists
- [x] There is a [Catena-X standard](https://catena-x.net/de/standard-library) referencing this model
- [x] The model is in status "release"
- [x] The model is not yet in status "standardize"
- [ ] Release note entry for model version referenced in standard received link to standard document

**Comment by bs-jokri** [comment]
Model file: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.0/BatteryPass.ttl

**Comment by bs-jokri** [comment]
closed by #280
