### ISSUE TITLE
[Model Deprecation]: PCF 4.0.0 

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-tractusx/sldt-semantic-models#275]
## Update Reason
there is a bugfix version of the PCF model. this one contains a bug in the example values and needs to be deprecated.

https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.pcf/4.0.0

## MS1 Criteria

- [ ] The model that should be deprecated exists and is not deprecated already
- [ ] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by bs-jokri** [comment]
@SMaierTSI is it ok to deprecate this model. I assume we missed to do that when releasing 4.0.1

**Comment by SMaierTSI** [comment]
@bs-jokri from my perspective the model can be deprecated because like you mentioned an updated version has been released. Not sure if any other use case utilizes the 4.0.0 model.
@catroest are there any reasons why we should keep the old 4.0.0 version? Latest version which has been released is 4.0.1.

**Comment by catroest** [comment]
@SMaierTSI we use it in the DPP 1.0.0

**Comment by catroest** [comment]
4.0.0

**Comment by bs-jokri** [comment]
Would it be possible to feed version 4.0.1 into the next version of DPP, so that we can harmonize the versions. Deprecation means the model will be removed after two releases (in case of pcf 4.0.0 this would be 3.4)

**Comment by catroest** [comment]
I would have to speak with our application team, because they implement the DPP 1.0.0 (which includes PCF 4.0.0), if it is possible to not use this version in two releases. I will come back with this topic on monday

**Comment by bs-jokri** [comment]
@catroest any updates? Can we deprecate?

**Comment by bs-jokri** [comment]
@agg3fe can you take over and create an PR to change status to deprecated when the OK is there from @catroest

**Comment by SMaierTSI** [comment]
sorry, we cannot mark v4.0.0 as deprecated. just heard from our implementation partners in the use case team that their solutions still rely on v4.0.0 in catena-x r3.2. they will probably move to a newer version in r23.12, so we have to postpone the "deprecated" status of the pcf v4.0.0 data model.

**Comment by bs-jokri** [comment]
@SMaierTSI according to the governance process deprecating means, that the model will be available for the next two cx releases. I would assume the proper way would be to mark 4.0.0 as deprecated. But I do not understand, why 4.0.0 is used as the standard references 4.0.1.

**Comment by SMaierTSI** [comment]
standard is being corrected, references now 4.0.0.
i think it would be a misleading signal to deprecate the version 4.0.0 which is used by the solutions we have, that's why i propose to postpone the deprecation. but i'm open for a discussion, just let me know how to proceed

**Comment by bs-jokri** [comment]
Ok, so this means we will not depreacte and bring up this issue again. Will close this issue for now
