### ISSUE TITLE
[Model Update]: Batch 2.0.0

### ISSUE THREAD

**Issue by BenediktMuellerIML** [eclipse-tractusx/sldt-semantic-models#281]
## Update Reason
Take out the properties "nameAtCustomer" and "customerId" and limit local identifiers to "manufacturerId" and "batchId" for complience reasons. 

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by BenediktMuellerIML** [comment]
modeling_team

**Comment by bs-jokri** [comment]
the change should be reflected by version number 2.0.0 as it contains breaking changes.

**Comment by bs-jokri** [comment]
MS1 approval given under the condition that a possible migration strategy is discussed with the team (add result as comment to this issue) @BenediktMuellerIML

**Comment by BenediktMuellerIML** [comment]
> with

There is one data provider that provides that model. They are already informed about that change.
