### ISSUE TITLE
[Model Deprecation]: essincident version 1.0.0 deprecate

### ISSUE THREAD

**Issue by birgitZF** [eclipse-tractusx/sldt-semantic-models#282]
## Update Reason

essincident version 1.0.0 shall be set to deprecate because new version 2.0.0 is not compatible to version 1.0.0. As version 1.0.0 is not in use by anyone it should be deprecated as soon as version 2.0.0 is released.

## MS1 Criteria

- [x] The model that should be deprecated exists and is not deprecated already
- [x] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [x] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by bs-jokri** [comment]
@agg3fe can you take over and create an PR to change status to deprecated?
