### ISSUE TITLE
[New Model]: Planned Production Output

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sldt-semantic-models#290]
## Model Description
PURIS (UC) wants to provide further information to evaluate the supply situation. One of this information is the planned production (quantity and date time matchings). It is complementary to product stock (find it [here](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.product_stock/1.0.0)). Together they should support identifying and mitigating shortages more actively.

## Relevant Standards
None

## Example Data
``` json
{
  "positions": [
    {
      "lastUpdatedOnDateTime": "2023-04-01T14:23:00+01:00",
      "allocatedProductionOutputs": [
        {
          "plannedProductionQuantity": {
            "unitOfMeasure": "GRM",
            "quantityNumber": 2.5
          },
          "productionSiteBpns": "BPNS0123456789ZZ",
          "estimatedTimeOfCompletion": "2023-04-01T14:23:00+01:00"
        }
      ],
      "orderPositionReference": {
        "supplierOrderId": "M-Nbr-4711",
        "customerOrderId": "C-Nbr-4711",
        "customerOrderPositionId": "PositionId-01"
      }
    }
  ],
  "materialNumberCatenaX": "urn:uuid:48878d48-6f1d-47f5-8ded-a441d0d879df",
  "materialNumberCustomer": "MNR-7307-AU340474.002",
  "materialNumberSupplier": "MNR-8101-ID146955.001"
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by tom-rm-meyer-ISST** [comment]
modeling_team

**Comment by bs-jokri** [comment]
@tom-rm-meyer-ISST ProductionForecast/ShopFloorInormationService could be checked if there are entities or characteristics included, which might can be reused
