### ISSUE TITLE
[New Model]: 

### ISSUE THREAD

**Issue by piyushmipart** [eclipse-tractusx/sldt-semantic-models#304]
## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by bs-jokri** [comment]
obsolete
