### ISSUE TITLE
[New Model]: RequestForQuotation

### ISSUE THREAD

**Issue by piyushmipart** [eclipse-tractusx/sldt-semantic-models#307]
## Model Description
Request for Quotation model is an information exchange between the buyers and suppliers. Suppliers want to receive all the relevant product manufacturing information and as precisely as possible. This is the role of the RFQ, It includes all the configurations such as material, tolerance class, BoM (bill of material)  and so on. 
This information which is referred to as product manufacturing informations(PMIs) will b forwarded to the suppliers which the buyers will select after the process of matchmaking is done. 

## Relevant Standards

Need to check which of the BoP (Bill of Process) standard can also be referenced with our standard here.

## Example Data

| UseCase   | "Level" | Property                      | mand./opt. | Semantic ID | Default value |
|-----------|---------|-------------------------------|------------|-------------|---------------|
| Function1 |         |                               |            |             |               |
|           |         | requestForQuotationSource     | optional   | string      |               |
|           |         | requestForQuotationId         | mandatory  | string      |               |
|           |         | requestForQuotationName       | mandatory  | string      |               |
|           |         | requestForQuotationDate       | mandatory  | string      |               |
|           |         | materialObject            | mandatory  | matrix?     |               |
|           |         | quantity                      | mandatory  | float       |               |
|           |         | quantityUnit                  | optional   | Enum        |               |
|           |         | generalTolerance              | mandatory  | Enum        |               |
|           |         | requiredDeliveryDate          | mandatory  | string      |               |
|           |         | surfaceTreatment              | optional   | enum        |               |
|           |         | additionalQualityRequirements | optional   | enum        |               |
|           |         | StandardsOffered              |            |             |               |
|           |         | testPartRequired              | optional   | boolean     | false         |
|           |         | additonalComments             | optional   | String      |               |
|           |         | billOfProcess                 | optional   | String      |               |
|           |         | stepFile                      | Mandatory  | String      |               |
|           |         | technischeZeichnung           | Optional   | String      |               |
|           |         | surfaceroughnessfinish        | optional   | float       |               |
|           |         | AnzahlGewinde                | optional   | integer     |               |
|           |         | AnzahlPassungen              | optional   | integer     |               |
|           |         | Warmbehandlung                | optional   | enum        |               |
|           |         | Name                          | Mandatory  | string      |               |
|           |         | Address                       | Mandatory  | string      |               |
|           |         | companyName                   | Optional   | string      |               |
|           |         | emailID                       | Mandatory  | string      |               |
|           |         | rechnungAddress               | Mandatory  | string      |               |
|           |         | deliveryAddress               | Mandatory  | string      |               |
|           |         | phoneNumber                   | Mandatory  | integer     |               |
|           |         | partdescription               | Optional   | string      |               |
|           |         | surfacefinishcolour           | Optional   | enum        |               |
|           |         | 3dTechnology                  | Optional   | enum        |               |
|           |         | technicalDrawingNumber        | Optional   | float       |               |
|           |         | revisionNumber                | Optional   | float       |               |
|           |         | deliveryRequirements          | Optional   | string      |               |
|           |         |                               |            |             |               |
|           |         |                               |            |             |               |

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided 
- [ ] 
[RFQ_Daten final review.xlsx](https://github.com/eclipse-tractusx/sldt-semantic-models/files/12646659/RFQ_Daten.final.review.xlsx)
in an example
[RFQ Example.pdf](https://github.com/eclipse-tractusx/sldt-semantic-models/files/12657270/RFQ.Example.pdf)

Structure : https://confluence.catena-x.net/display/ARTIV/CX+-+0000+Request+for+Quotation+Aspect+Model+v.1.0.0

In case of the 'BoM' data field, the actual structure looks like in the above pasted pdf file. Please support in getting the format right. Appreciate your inputs.

**Comment by nbarysch** [comment]
Modeling_Team

**Comment by agg3fe** [comment]
please check the existing properties from aspects e.g. BOM models
