### ISSUE TITLE
[New Model]: IdBasedComment for DCM use case

### ISSUE THREAD

**Issue by nhaenis** [eclipse-tractusx/sldt-semantic-models#308]
## Model Description
DCM needs a model to exchange comments on entities between partners for the use case collaboration.

## Example Data
--- JSON only payload suggestion ---
``` JSON
{
  "commentId": "f5c151e4-30b5-4456-94fd-2a7b559b6121",
  "objectId": "dfeb1334-497e-4dab-97c1-4e6f4e1c0320"
  "postingBpnl": "BPNL6666666666YY",
  "postedAt": "2023-03-10T12:27:11.320Z",
  "changedAt": "2023-03-10T12:27:11.320Z",
  "author": "someone@company.com",
  "commentType": "information",
  "calendarWeeks": [
    "2023-07-01"
  ],
  "commentText": "Hello, this is a comment!",
  "requestDelete": true,
}
```

## MS1 Criteria
- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by nhaenis** [comment]
@modelling_team

**Comment by agg3fe** [comment]
some changes to the property name will happen.  e.g. calendarWeeks.
