### ISSUE TITLE
[Model Update]: Return Request v2.0.0

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#313]
## Update Reason
- add attributes: manufacturingPartID, OeNumber, mileage, productionDate, areaOfUsage, deliveryAddress, productGroup, arrivalDateAtCustomer

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by DanielSteffenReichert** [comment]
Link to the current version of the return request model (v1.1.2)

https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.return_request/1.1.2

**Comment by agg3fe** [comment]
The discussion is required on providing the 'deliveryAdress' in the model
