### ISSUE TITLE
[New Model]: Software Information 1.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#314]
## Model Description
To ensure the traceability of electronic parts (such as ECUs), it is important to be able to track the associated software information. 

Advantages of a software aspect model:
- no digital twin for each software is necessary (so that it is not necessary to have a separate part number of each used software in a product).
- it is possible to find out what kind of software is installed at a part.

## Relevant Standards
No relevant standards available

## Example Data
```json
{
  "catenaXId": "urn:uuid:454ffa8e-f88d-4ad1-be45-06981756aeb1",
  "softwareInformation": [
    {
     "name": "ECU Software XY12345",
      "softwareId": "SW12345678",
      "version": "1.2.0",
      "lastModifiedOn": "2023-03-21T08:17:29.187+01:00"
    },
    {
      "name": "Software ABC",
    "softwareId": "SW12345678",
      "version": "3.0.0",
      "lastModifiedOn": "2023-03-21T08:17:29.187+01:00"
    }
  ]
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by johannsvarela** [comment]
FYI @BenediktMuellerIML @jonbckr

**Comment by agg3fe** [comment]
Further internal discussions would be required to refine the model to cover every scenario/problem

**Comment by agg3fe** [comment]
The proper naming of model would be required as 'Software' is very generic term here
