### ISSUE TITLE
[Model Update]: Reuse Certificate v2.0.0

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#324]
## Update Reason

- add attributes: Article Number, VIN, OE number, Issuer, issue date, Dismantler, CatenaXId Previous Life, Catena X ID, serial number.

Link to the current version of the Reuse Certificate (v1.0.0)
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.reuse_certificate/1.0.0

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by bs-jokri** [comment]
In version 1.0.0 of the certificate a shared aspect
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.shared.recycling_strategy_certificate/1.0.0/RecyclingStrategyCertificate.ttl
was used. It should be clarified if this structure can also be realized in the new version of the certificate.

**Comment by bs-jokri** [comment]
Modeling Steward: @agg3fe support by @bs-jokri
