### ISSUE TITLE
[Model Update]: Refurbishing Certificate v2.0.0

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#326]
## Update Reason
- add attributes: Article Number, VIN, OE number, Issuer, issue date, Dismantler, CatenaXId Previous Life, Catena X ID, serial number.

Link to the current version of the return request model (v1.0.0)
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.refurbishing_certificate/1.0.0

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by bs-jokri** [comment]
Modeling Steward: @agg3fe  support by @bs-jokri
