### ISSUE TITLE
[New Model]: Waste Certificate v1.0.0

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#327]
## Model Description
The Waste-Certificate marks the point in time, respectively status update at which an asset irrevocably enters the status through tranferring to an authorized business partner. Materials send to landfill are mostly inert and are for example slag, waste from thermal recycling and minerals.

Following attributes are necessary: Article Number, VIN, OE number, Issuer, issue date, Dismantler ID, CatenaXId Previous Life, Catena X ID, revocationDate.

## Example Data
https://confluence.catena-x.net/pages/viewpage.action?pageId=100930634

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by bs-jokri** [comment]
structure of certificate is similar to other recycling certificates. Hence, it should be checked if the shared aspect
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.shared.recycling_strategy_certificate/1.0.0/RecyclingStrategyCertificate.ttl
can be reused.

**Comment by bs-jokri** [comment]
structure of certificate not yet standardized. Thus no reference to standard possible

**Comment by bs-jokri** [comment]
Modeling Steward: @agg3fe support by @bs-jokri
