### ISSUE TITLE
[New Model]: Material Recycling Certificate V1.0.0

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#328]
## Model Description
The Material-Recycling Certificate marks the point in time, respectively status update at which an asset irrevocably enters a new status through transferring to an authorized business partner. In most cases the authorized partner is a shredder company and/or a recycler.

Following attributes are necessary: Article Number, VIN, OE number, Issuer, issue date, Dismantler ID, CatenaXId Previous Life, Catena X ID, revocationDate.

## Example Data
https://confluence.catena-x.net/pages/viewpage.action?pageId=100928321

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by bs-jokri** [comment]
It should be checked if the shared aspect 
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.shared.recycling_strategy_certificate/1.0.0/RecyclingStrategyCertificate.ttl
can be used to model the certificate.

**Comment by bs-jokri** [comment]
Modeling Steward: @agg3fe support by @bs-jokri
