### ISSUE TITLE
[Model Update]: BOMAsSpecified

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#36]
## Update Reason

Request from TC4S:
-	BoMAsSpecified describes top down View from a OEM (Producer) of the vehicle. How is this releated to other BOM View (e.g. in Traceability)? As we using common data elements? Shouldn’t we rather have a standardization document on BoM in general and describe, when to use which view (irrespective of a use case)? 
o	related to other BOM view in that sense, that they both depict the structure of the specified/buit/etc. asset. In contrast to Traceability, this BOM addresses the full asset how it should be set-up and that an OEM is responsible for. It is not affected by missing supplier as it is in the traceabilty BOMs, where a component cannot be provided as soon as the respective supplier is not part of Catena-X. The BOMAsSpecified tries to cope with the BOM approaches, but cannot be addressed by the same structure and therefor is an own data model
-	Which other standards have been looked at before we created our own BoM view? IDTA is currently in the specification phase of a BoM model in Industry4.0 context – has there been any alignment between Catena-X and IDTA? 
o	[@Sasan.Baba-esfahani@bmw.de](mailto:Sasan.Baba-esfahani@bmw.de): Habt ihr hier was abgestimmt mit der IDTA zu Hierachical Structures enabling Bills of Material Submodel?
-	Why do we create only a BOM without references to other DT? 
o	The catenaXIds can be added for self-explanation but the actual lookup should be focused on a combination of ownerPartNumber and ownerId (BPN)
-	Description & item category description are 100% identical (copy paste)  does not make sense 
o	[@Sasan.Baba-esfahani@bmw.de](mailto:Sasan.Baba-esfahani@bmw.de)
-	Part: Description is TBD  This is not adequate for public release 
o	[@Sasan.Baba-esfahani@bmw.de](mailto:Sasan.Baba-esfahani@bmw.de)

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by mthiers** [comment]
core team:
all points can be omitted according to @Tram Kevin except for part description

@Kevin tram will deliver description until 23.01.2023 EOB
MS1 approval given
(@bs-jokri  will do post documentation)

**Comment by Kevinataccenture** [comment]
TBD should be replaced with: 
The description of the part in the primary language of the production facility of the product owner.

**Comment by mthiers** [comment]
Attachment won't be changed due to semantic standards. Nevertheless, characteristics will be changed in the future to cover upload of multiple attachments -> DONE: changed to set already (we agreed to change it if there were already more changes to the model)
Quantity will be changed as in the comment above from Marcel. In addition the description will be changed to "The available quantity of an offered product". -> DONE
Status will be excluded as above -> DONE
Certificate will be excluded as above -> DONE
GeographicalCoordinate: Add description to: Location coordinates -> Description already included in longitude and latitude, therefore description of geographical coordinates given

**Comment by bs-jokri** [comment]
closed by #48
