### ISSUE TITLE
[Model Update]: Return Request

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#38]
## Update Reason
-	Desired price: No description; unclear how desired price relates to a return request.
-	Last return data – Typo
-	Needs return – typo
-	Request data: talks about a date in GMT time zone. Is it a timestamp according to ISO 8601? Typically, timestamps are reference to UTC. Where would I find that definition?

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by mthiers** [comment]
bullet point 1. "Price the manufacturers are willing to pay for this part after EoL of a car." -> @kevinataccenture can not be found in most current version 1.1.1 (missing in semantic hub) therefore I assume this comment ist obsolete and can be ignored

bullet point 4. "Request data: talks about a date in GMT time zone. Is it a timestamp according to ISO 8601? Typically, timestamps are reference to UTC. Where would I find that definition?" --> change description to "Describes until when the request is valid." -> changed for request date and latest return date
