### ISSUE TITLE
[Model Update]: MaterialforHomologation

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#39]
## Update Reason
-	Calculation Logic???
-	VDA Standard ID – Unclear what it is. Where is the reference/repository that defines the potential values for this. No example is given.
-	Name field fixed between VDAStandardID and Standard. What name is it. The name of the standard, of the material, ??? Modelling should be enhanced
-	ANNEX  EXTREMELY HARD TO read, very pixely when zoomin in. What is the purpose, who should use this?

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by mthiers** [comment]
core team meeting:
@Kevin Tram will delivere feedback until 24.01.2023 EOB

**Comment by Kevinataccenture** [comment]
No change of the model needed. Comments will be clarified in the standardization document

**Comment by mthiers** [comment]
according to @Kevinataccenture : close this issue

**Comment by bs-jokri** [comment]
Will be closed according to response
