### ISSUE TITLE
[Model Update]: RecyclingStrategyCertificate_v2.0.0 (SharedAspects)

### ISSUE THREAD

**Issue by yuchengluo1** [eclipse-tractusx/sldt-semantic-models#397]
## Update Reason
new attributes: article number, VIN, OE number, dismantler ID, serial number, revocation date.

original version: 
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.shared.recycling_strategy_certificate/1.0.0

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by agg3fe** [comment]
Modeling_Team
