### ISSUE TITLE
[Model Update]: BatteryPass

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#40]
## Update Reason
-	FIELD batterie identification: description unclear what is it, potential vlues, missing examples
-	Cell chemistry – same as identification - unclear
-	Document: Field name is singular, description talks about set of documents – unclear
-	Manufacturer: Field name is manufacturer, description is LE that sells and invoices the battery. Seems wird. Either description should be entity who manufacturs the batterie or field name should be renamed
-	Address: Reference to BPDM ery generic, difficult to understand for consumer of the document. Where does he get further information?
-	Unclear on thoroughfare, locality postal delivery point, and premise attribute  isn’t that in conflict with BPDM BPN concept (site is a BPN)?
-	Contact entity: Shouldn’t this be also aligned with BPDM? Website, email, phone number. Are these very specific to the batterie, or related to the manufacturer?
-	Battery model: description says battery type  Typo/Copy paste
-	Manufacturer: Is there any reference to a globally valid manufacturer ID like the VDMA Manufacturer ID code, GS1 Global Location Number, Catena-X BPN, ….) Just haing a full text name does not seem to be sufficient
-	Entity name “material number and weight an percentage” is weird; shouldn’t there be a better common name ?
-	In physical dimension entity there is also weight included??? Unclear?

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by mthiers** [comment]
core team round:
according to Kevin tram all bullet points can be ignored except for "Entity name “material number and weight an percentage” is weird; shouldn’t there be a better common name ?"

**Comment by Kevinataccenture** [comment]
After refinement with Thorsten, the following points are added:
- Change the the copyright from "Badische Anilin und Sodafabrik societates Europaea" to "BASF SE"
- :BatteryVoltageCharacteristiC - large "C" at the end
- :RatedCapacityCharacteristic - the description states "The total number of ampere-hours (Ah) ..." - the  bamm-c:unit unit:ampere. is ampere though, not ampere hours.
- :OhmCharacterisitic - Typo. Characterisitic to be changed to Characteristic. Also in the bamm:preferredName "ohm characterisitic"@en;
- Same type in :BatteryEnergyCharacterisitc, (and please again check the bamm:preferredName - same!)
- Same typo in :CycleLifeTestCRateCharacterisitc
- :capacityThresholdExhaustion - the [bamm:preferredName here](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.0/BatteryPass.ttl#L354) is wrong (looks like a copy-paste issue from the lines above). It's not "internal resistance".
- :energyRoundtripEfficiencyChange - same as above, the preferredName should be "energy roundtrip efficiency change"@en;
- :originalPower }}and {{originalPowerCapability look like they do the same job? Both have the same preferredName, too.
The picture attached still refers to KilowattCharacteristic and WattCharacteristic - has this changed in v.3.? (TD: I cannot find it any more)
- :batteryType and :batteryModel have the same description - copy-paste issue (see [CMP-431](https://jira.catena-x.net/browse/CMP-431) for a suggestion on the description)
- Misspelled "material" in model with "matierial": :matierialPercentageMassFraction, :matierialWeight, :MatierialPercentageMassFractionCharacteristic 
- Inconsistency in using a small letter for a property and a capital letter as first letter. Any reason for this?
EnergyRoundtripEfficiencyChangeCharacterisitic   (looks like "PascalCase") but originalPower ("camelCase")
-

**Comment by mthiers** [comment]
Change the the copyright from "Badische Anilin und Sodafabrik societates Europaea" to "BASF SE" - DONE
    :BatteryVoltageCharacteristiC - large "C" at the end - DONE changed to lower case
    :RatedCapacityCharacteristic - the description states "The total number of ampere-hours (Ah) ..." - the  bamm-c:unit unit:ampere. is ampere though, not ampere hours. - @Kevinataccenture : sooo.....???!?
    :OhmCharacterisitic - Typo. Characterisitic to be changed to Characteristic. Also in the bamm:preferredName "ohm characterisitic"@en; - DONE changed to all occurences of "Characterisitic" to "Characteristic"
    Same type in :BatteryEnergyCharacterisitc, (and please again check the bamm:preferredName - same!)
    Same typo in :CycleLifeTestCRateCharacterisitc
    :capacityThresholdExhaustion - the [bamm:preferredName here](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.0/BatteryPass.ttl#L354) is wrong (looks like a copy-paste issue from the lines above). It's not "internal resistance". - DONE change to "capacity threshold exhaustion"
    :energyRoundtripEfficiencyChange - same as above, the preferredName should be "energy roundtrip efficiency change"@en; - DONE changed to "energy roundtrip efficiency change"
    :originalPower }}and {{originalPowerCapability look like they do the same job? Both have the same preferredName, too.
    The picture attached still refers to KilowattCharacteristic and WattCharacteristic - has this changed in v.3.? (TD: I cannot find it any more) - @Kevinataccenture : sooo.....???!?
    :batteryType and :batteryModel have the same description - copy-paste issue (see [CMP-431](https://jira.catena-x.net/browse/CMP-431) for a suggestion on the description) - @Kevinataccenture : sooo.....???!? the example does not help
    Misspelled "material" in model with "matierial": :matierialPercentageMassFraction, :matierialWeight, - DONE changed all occurences of "matierial" to "material"
:MatierialPercentageMassFractionCharacteristic 
    Inconsistency in using a small letter for a property and a capital letter as first letter. Any reason for this? 
    EnergyRoundtripEfficiencyChangeCharacterisitic   (looks like "PascalCase") but originalPower ("camelCase") - yes, conventions
    Add examples for Battery Identification: X123456789012X12345678901234567 - wrong place for example, already included in model see "batteryIDDMCCode"
    Add examples for cellChemistry: LFP, Natrium, Li-Ion, NMC, NCA - wrong place for example, already included in model see "battery type"

**Comment by Kevinataccenture** [comment]
:RatedCapacityCharacteristic - the description states "The total number of ampere-hours (Ah) ..." - the bamm-c:unit unit:ampere. is ampere though, not ampere hours. - @Kevinataccenture : sooo.....???!?
--> change line 537 in TTL to ampere-hours

:originalPower }}and {{originalPowerCapability look like they do the same job? Both have the same preferredName, too.
The picture attached still refers to KilowattCharacteristic and WattCharacteristic - has this changed in v.3.? (TD: I cannot find it any more) - @Kevinataccenture : sooo.....???!?
--> need to be clarified

:batteryType and :batteryModel have the same description - copy-paste issue (see [CMP-431](https://jira.catena-x.net/browse/CMP-431) for a suggestion on the description) - @Kevinataccenture : sooo.....???!? the example does not help
--> change description of BatteryModel: change battery type to batterymodel

**Comment by bs-jokri** [comment]
closed with https://github.com/eclipse-tractusx/sldt-semantic-models/pull/68
