### ISSUE TITLE
[New Model]: Planned Delivery Information V1.0.0

### ISSUE THREAD

**Issue by zanpi8020** [eclipse-tractusx/sldt-semantic-models#400]
## Model Description
Planned delivery information plays a crucial role in proactively tracking, managing, and assessing the timely fulfillment of customer orders from various suppliers in order to avoid shortages and bottlenecks. Relying on manual methods like phone calls, or email correspondence for collecting this data can introduce errors, does not include last-minute nor real-time updates, and can potentially cause shortages.

One effective strategy to address these challenges involves the sharing of planned delivery information among Catena-X business partners, ensuring compatibility and interoperability. Establishing a standardized semantic definition to describe planned delivery information is a fundamental step in enabling this exchange to occur efficiently, thereby maximizing the potential solutions available for mitigating any potential supply shortages.

## Relevant Standards
There are no relevant standards available, however, this standard is reusing some of existing elements from other Catena-X standards - (PURIS) 8.1.2.1 Item Stock. It is also closely related to Actual Delivery Information Standard v.1.0.0.

## Example Data

```json
{
  "PlannedDeliveryInformation": [
    {
      "OrderId": {
        "supplierOrderId": "M-Nbr-4711",
        "customerOrderId": "C-Nbr-4711",
        "customerOrderPositionId": "PositionId-01"
      },
      "ShippingInformation": {
        "EstimatedTimeOfArrival": "06/10/2023",
        "EstimatedTimeOfDeparture": "01/11/2023",
        "ShipmentType": "Train",
        "TransitPoints": "3",
        "Delays": "-1 day"
      },
      "quantityOnAllocatedStock": "356kg",
      "UnitofDelivery": "kg",
      "ObjectInformation": {
        "supplierItemNumber": "JAGW2879341S",
        "customerItemNumber": "5544326936",
        "conditionofGoods": "new"
      }
    }
  ]
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by zanpi8020** [comment]
Modeling_Team

**Comment by agg3fe** [comment]
Please also align with DCM team.
