### ISSUE TITLE
[New Model]: Actual Delivery Information V1.0.0

### ISSUE THREAD

**Issue by zanpi8020** [eclipse-tractusx/sldt-semantic-models#403]
## Model Description
Actual delivery information plays a crucial role in tracking, managing, and assessing the timely fulfillment of customer orders from various suppliers in order to avoid shortages and bottlenecks. Relying on manual methods like phone calls, or email correspondence for collecting this data can introduce errors, does not include last-minute nor real-time updates, and can potentially cause shortages.

One effective strategy to address these challenges involves the sharing of actual delivery information among Catena-X business partners, ensuring compatibility and interoperability. Establishing a standardized semantic definition to describe actual delivery information is a fundamental step in enabling this exchange to occur efficiently, thereby maximizing the potential solutions available for mitigating any potential supply shortages.

In this document, the actual delivery information is described and standardized.

Actual Delivery information is closely related to #400 

## Relevant Standards
There are no relevant standards available, however, this standard is reusing some of existing elements from other Catena-X standards - (PURIS) 8.1.2.1 Item Stock. It is also closely related to Planned Delivery Information Standard v.1.0.0.

## Example Data
```json
{
  "PlannedDeliveryInformation": [
    {
      "OrderId": {
        "supplierOrderId": "M-Nbr-4711",
        "customerOrderId": "C-Nbr-4711",
        "customerOrderPositionId": "PositionId-01"
      },
      "ShippingInformation": {
        "EstimatedTimeOfArrival": "06/10/2023",
        "EstimatedTimeOfDeparture": "01/11/2023",
        "ActualTimeOfDeparture": "06/10/2023",
        "ActualTimeOfArrival": "19/10/2023",
        "ShipmentType": "Train",
        "TransitPoints": "3",
        "DeliveryPoint": "Tomsiceva street 1, 1000 Ljubljana, Slovenia",
        "Delays": "+1dayT07:00"
      },
      "quantityOnAllocatedStock": "356 kg",
      "UnitofDelivery": "375 kg",
      "OrderDifference": "+50 kg",
      "ActualOrderDifference": "+ 15 kg",
      "ActualQuantity": "375 kg",
      "PlannedOrderDifference": "5 kg",
      "ObjectInformation": {
        "supplierItemNumber": "JAGW2879341S",
        "customerItemNumber": "5544326936",
        "conditionofGoods": "new",
        "Damages": "none"
      },
      "deliveryStatus": "Delivered",
      "TrackingNumber": "CR8465654984656DE",
      "TransitTime": "1dayT02:00"
    }
  ]
}
```
## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by zanpi8020** [comment]
Modeling_Team

PS: I won't be available next week, but other team members will jump in on my behalf

**Comment by agg3fe** [comment]
Please check if any alignment with DCM is required.

**Comment by nhaenis** [comment]
> Please check if any alignment with DCM is required.

I can't see any DCM related information in this requested model. DCM planning horizon is 6 up to 24 months and does not deal with orders yet.
From a planning perspective, PURIS would be closer to the order process than DCM, but I don't know if they are already linked to this information. Please contact @tom-rm-meyer-ISST  for more information.
