### ISSUE TITLE
[Model Update]: IdBasedRequestForUpdate

### ISSUE THREAD

**Issue by nhaenis** [eclipse-tractusx/sldt-semantic-models#409]
## Update Reason
Due to the harmonization from `WeekBasedMaterialDemand` to the new `MaterialDemand` aspect model with PURIS the property `weekBasedMaterialDemand` in the RfU aspect needs to be changed to `materialDemand`:
```json
{
  -- "weekBasedMaterialDemand" : [ {
  "materialDemand" : [ {
    "materialDemandId" : "0157ba42-d2a8-4e28-8565-7b07830c3456",
    "changedAt" : "2023-03-10T12:27:11.320Z"
  } ],
  "weekBasedCapacityGroup" : [ {
    "capacityGroupId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
    "changedAt" : "2023-03-10T12:27:11.320Z"
  } ]
}
```

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by nhaenis** [comment]
@modeling_team

**Comment by agg3fe** [comment]
This will add a new major version 2.0.0
