### ISSUE TITLE
[Model Update]: Marketplace

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#41]
## Update Reason
-	Marketplace offer is a transactional context towards a marketplace. We do need a standardized format for this for sure. However, why is this a AAS submodel? This seems a bit strange
-	Catena-X Identifier: Strange Name. It seems this is an Offer ID (like a purchase order or sales order number). Calling it Catena-X ID is strange as it does not describe the business context of this attribute.
-	Atachment: Field is singular, description is plural – unclear.
-	Burned, corroded, discoloured are all conditions, but there is also a condition field. Unclear how this is modelled by going through the document
-	Field condition: description just states condition – unclear
-	Marketplace product: What is it? No description
-	Price: gross price, net price? What about tax determination/calulation? What is this price?
-	Quantity = type string? Shouldn’t this be an INT?

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by mthiers** [comment]
core team round: 
bullet point 1. + 2. + 4. + 5. + 6.  can be ignored according to Kevin Tram
- plural attachments: check if modelled as set, if so naming remains as singular
- quantity: to be clarified with business side

**Comment by mthiers** [comment]
core team round:

additional update reasons:
<html>
<body>


Property / Entity | Suggested Change | Comment
-- | -- | --
Attachment | Should be plural |  
Quantity | Should be type integer / float |  
Status (draft, published) | Exclude from MarketPlaceOffer (for standardization process) (TBD) |  
Attachment Entity | Rename (TBD) |  
Certificate Entity | Exclude from MarketPlaceOffer (for standardization process) (TBD), certificates can be attached as attachments |  
GeographicalCoordinate | Add description


</body>
</html>

**Comment by mthiers** [comment]
core team round:
MS1 approval given

(@bs-jokri  will do postdocumentation)

**Comment by Kevinataccenture** [comment]
We had another discussion with Maria Fay & Marcel with the following decisions:
- Attachment won't be changed due to semantic standards. Nevertheless, characteristics will be changed in the future to cover upload of multiple attachments
- Quantity will be changed as in the comment above from Marcel. In addition the description will be changed to "The available quantity of an offered product".
- Status will be excluded as above
- Certificate will be excluded as above
- GeographicalCoordinate: Add description to: Location coordinates

**Comment by mthiers** [comment]
Attachment won't be changed due to semantic standards. Nevertheless, characteristics will be changed in the future to cover upload of multiple attachments -> DONE: changed to set already (we agreed to change it if there were already more changes to the model)
    Quantity will be changed as in the comment above from Marcel. In addition the description will be changed to "The available quantity of an offered product". -> DONE
    Status will be excluded as above -> DONE
    Certificate will be excluded as above -> DONE
    GeographicalCoordinate: Add description to: Location coordinates -> DONE
