### ISSUE TITLE
[New Model]: business partner certificates 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sldt-semantic-models#415]
## Model Description

A semantic data model for business partner certificates is a structured representation of data that defines the relationships, attributes, and meaning of various elements related to certificates issued to or by business partners. Such a model helps solution providers and data providers to manage and validate certificates.

This model serves as a foundation for database design, data governance, interfaces and application development in the context of certificates and their associated business partners.

**Responsibles for this topic:**
@SujitMBRDI , @maximilianong

## Relevant Standards
Standard comes with the release 24.03.

## Example Data
The data model describes the attributes for business partner certificates.
[Catena-X Semantic Model Certificates.xlsx](https://github.com/eclipse-tractusx/sldt-semantic-models/files/13349139/Catena-X.Semantic.Model.Certificates.xlsx)

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example
- [ ] A modeling steward has been assigned

**Comment by agg3fe** [comment]
@modeling_team

**Comment by agg3fe** [comment]
Let's wait for the IP approval and then we go for approval afterwards.

**Comment by maximilianong** [comment]
@agg3fe I updated the issue with the data model.

**Comment by agg3fe** [comment]
> @agg3fe I updated the issue with the data model.

Thanks. Issue Approved.

**Comment by chr-krenn** [comment]
@maximilianong : just a note - this is my account. BTW- will check how to integrate TISAX specifis
