### ISSUE TITLE
[Model Update]: bamm:io.catenax.fleet.claim_data:1.0.0 to version 2.0.0 with SAMM

### ISSUE THREAD

**Issue by TorstenHirsch** [eclipse-tractusx/sldt-semantic-models#417]
## Update Reason
The use case quality group decided to upgrade this model to version 2.0.0: 
- Use new versions of ESMF toolings
- Convert from BAMM to SAMM
- Make adaptions in model structure

## MS1 Criteria

- [X] The model that should be updated exists
- [X ] The referenced use case exists: It is use case CX QAX
- [X] The potential updates are discussed with all stakeholders
- [X] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
--> new version will be 2.0.0
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [X] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by agg3fe** [comment]
@modeling_team
