### ISSUE TITLE
[New Model]: early warning notification

### ISSUE THREAD

**Issue by Timothy-Ra** [eclipse-tractusx/sldt-semantic-models#421]
## Model Description
The new model enables the notification function about findings from joint field monitoring between two participants fo the supply chain. This functionality is part of the early warning feature from the use case quality.

## Relevant Standards
It belongs to the same group of aspects as the MessageHeader Aspect Model: io.catenax.shared.message_header
 
## Example Data
{
  "header": {
    "senderBpn": "BPNL7588787849VQ",
    "relatedMessageId": "d9452f24-3bf3-4134-b3eb-68858f1b2362",
    "expectedResponseBy": "2023-06-19T21:24:00+07:00",
    "context": "urn:samm:io.catenax.<ASPECT-MODEL-NAME>:1.x.x",
    "messageId": "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9",
    "receiverBpn": "BPNL6666787765VQ",
    "sentDateTime": "2023-06-19T21:24:00+07:00",
    "version": "urn:samm:io.catenax.message_header:1.0.0"
  },
  "content": {
    "qualityAppFilter": {
      "uniqueIdentifiers": [
        {
          "serialPartNumber": "436347347.4343884384.FTG.538348",
          "anonymizedVIN": "3747429FGH382923974682",
          "catenaXId": "urn:uuid:c227a880-b82b-40f7-846c-3942ddf26c29"
        }
      ],
      "populationFilter": [
        {
          "aspectModel": "urn:bamm:io.catenax.manufactured_parts_quality_information:1.0.0",
          "filters": [
            {
              "from": "2019-02-01T00:00:00",
              "to": "2019-07-30T23:59:59",
              "aspectProperty": "production.productionDate",
              "dataType": "daterange",
              "valueList": [
                {
                  "value": "123-0.740-3434-A"
                }
              ]
            }
          ]
        }
      ]
    },
    "earlyWarningAttachmentLink": "subprotocolBody: catalogEndpoint=https://test.com/catalog;dataset=79afc338-f7ea-4255-a17d-ba6faf40d2b5",
    "anomalyDescription": "There is an unusual number of DTCs occuring in the population described by the property qualityAppFiilter",
    "qualityTaskID": "BPN-811_2022_000001"
  }
}

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by TorstenHirsch** [comment]
@modeling_team

**Comment by agg3fe** [comment]
This is going to be a new model and going to consume shared MessageHeader Aspect Model: io.catenax.shared.message_header

**Comment by Timothy-Ra** [comment]
@agg3fe we updated our model according to the MS2 criteria
You find the pull request with new ttl and sample json [here](Timothy-Ra:Timothy-Ra-patch-1)

Can you please check for MS2.

**Comment by Timothy-Ra** [comment]
@modeling_team please check for MS2
