### ISSUE TITLE
[Model Update]: IotSensorData 

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#427]
## Update Reason
After alignment meetings with IDTA and TC4S, the Assset Tracking Use Case have decided to change/update the aspect model IotSensorData. This update will keep the solution ATP interoperable and open. 

- The sensor's data attributes will be changed from static to dynamic.
- Conversion from BAMM to SAMM

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by Cvetanka-ZF** [comment]
@modeling_team

**Comment by agg3fe** [comment]
Modifying https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.iot_sensor_data
