### ISSUE TITLE
[Model Update]: IotSensorDeviceDefinition

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#428]
## Update Reason
Use Case Asset Tracking decided to upgrade the model to a new version.

- Convert from BAMM to SAMM

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by Cvetanka-ZF** [comment]
@modeling_team

**Comment by agg3fe** [comment]
Modifying https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.iot_sensor_device_definition.
Changing from Bamm to Samm.
