### ISSUE TITLE
[New Model]: Decommissioning Certificate

### ISSUE THREAD

**Issue by DanielSteffenReichert** [eclipse-tractusx/sldt-semantic-models#43]
## Model Description
This certificate is the statement of the issuer to properly decommission a certain object, which might be a vehicle or another product like high-voltage batteries.{color}

https://jira.catena-x.net/browse/CEC-1397

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by DanielSteffenReichert** [comment]
@bs-jokri Johannes can you please check my authorization rights for setting labels, assignees, etc. I currently cannot set these and label the models correctly. Thanks!

**Comment by ZazraltMagic** [comment]
- Use case is CE
- Standards are in the jira ticket linked
- First draft is modelled in BAMM with Sasan
