### ISSUE TITLE
[Model Deprecation]: PartSiteInformationAsPlanned 1.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#443]
## Update Reason
Since a new shared PartSiteInformationAsBuilt model is needed, this version (incl. CX-0094 PartSiteInformationAsPlanned standard) will be set to 'deprecate'. An issue for the new shared PartSiteInformation model is already created (#442) and is **mandatory before** the model can be **set to deprecate**.

## MS1 Criteria

- [x] The model that should be deprecated exists and is not deprecated already
- [x] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by agg3fe** [comment]
deprecate https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.part_site_information_as_planned/1.0.0/PartSiteInformationAsPlanned.ttl

**Comment by johannsvarela** [comment]
@modeling_team
