### ISSUE TITLE
[Model Update]:Convert Battery Pass 3.0.1 from BAMM to SAMM

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sldt-semantic-models#444]
# Update Reason 
We have battery pass model 3.0.1 which is standardized, but it is written in BAMM. We need to convert it from BAMM to SAMM.
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl

**Comment by agg3fe** [comment]
new SAMM version (4.0.0) coming in future. already in progress.

**Comment by jacewski-bosch** [comment]
@agg3fe please close
