### ISSUE TITLE
[Model Update]: Quantity error

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#446]
## Update Reason
areaUnit has the wrong example value (payload should not fit schema)
@tom-rm-meyer-ISST 

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by agg3fe** [comment]
Just change the example value 'samm:exampleValue "unit:litre"^^samm:curie;'
