### ISSUE TITLE
[Model Update]: io.catenax.shared.message_header V.2.0.0

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#469]
## Update Reason

We want to correct the current message header model (e.g. Traits) so it is semantically correct. 

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by agg3fe** [comment]
Is this new model backward compatible with existing version? If not, then it would make sense to create new model with major version change, v2.0.0

**Comment by BenediktMuellerIML** [comment]
> Is this new model backward compatible with existing version? If not, then it would make sense to create new model with major version change, v2.0.0

We talked about it will do a v2.0.0.

**Comment by johannsvarela** [comment]
@agg3fe Since our colleague who created this issue is on vacation for the next two weeks, we can't adapt this issue. Therefore we can create a new Issue and you can close this one. What's your opinion?

**Comment by agg3fe** [comment]
> @agg3fe Since our colleague - who created this issue - is on vacation for the next two weeks, we can't adapt this issue. Therefore we can offer you to create a new Issue, so that you can close this one. What's your opinion?

if only change is changing the version, I can also do that if you want. If there is any other change also, then we create new one.

**Comment by johannsvarela** [comment]
> > @agg3fe Since our colleague - who created this issue - is on vacation for the next two weeks, we can't adapt this issue. Therefore we can offer you to create a new Issue, so that you can close this one. What's your opinion?
> 
> if only change is changing the version, I can also do that if you want. If there is any other change also, then we create new one.

@agg3fe then lets keep this issue and you only change the title for us :-) We will link the PR to fix the bug soon.
