### ISSUE TITLE
[Model Deprecation]: Shared MessageHeader 1.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#507]
## Update Reason
Since we identified bugs of missing connection between a few properties and those respective traits, we have fixed this bug within the PR #476. Therefore the current version of this aspect model must be set deprecate. 

## Example Data
still the same as the version 1.0.0

## MS1 Criteria

- [ ] The model that should be deprecated exists and is not deprecated already
- [ ] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by jacewski-bosch** [comment]
@jacewski-bosch please check if used by any released models.
