### ISSUE TITLE
[Model Deprecation]: SingleLevelBomAsBuilt 1.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#509]
## Update Reason
Since the SingleLevelBomAsBuilt aspect model is part of the Industry Core, the latest version 2.0.0 will be optional for the standard R24.03 and mandatory for standard R24.05. Therefore the previous version 1.0.0 should be set to 'deprecate'. 

## MS1 Criteria

- [x] The model that should be deprecated exists and is not deprecated already
- [x] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by johannsvarela** [comment]
modeling_team

**Comment by johannsvarela** [comment]
FYI @jacewski-bosch @BenediktMuellerIML @jonbckr

**Comment by jacewski-bosch** [comment]
The model that should be deprecated exists and is not deprecated already --> OK
 The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect) --> OK
 A shared aspect, which will be deprecated, is not used by any released aspect model --> does not apply
