### ISSUE TITLE
[New Model]: Bill of Process (BoP)

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sldt-semantic-models#511]
*Resiliency Domain / Modular Production*

## Model Description

A Bill of Process (BoP) describes the best-practice approach for the production of a product. Detailed information about the processes, process precedence, and process parameters are required to manufacture the product. The exchange of process information between actors requires a standardized representation of the processes, as currently there are often separate, actor-specific forms of process representation.

This standardization effort aims to ease the understanding of process representations from other partners along the value chain by providing a shared model.
The scope of this model is a BoP that exists before actual production starts, therefore named "BoP as planned".
This model is meant to be flexible enough to accommodate a wide range of use cases and is relevant for both: information exchange (external) and internal workflows.

## Example Data

```json
{
  "productVersion": "1.4",
  "versionDataModel": "1.0",
  "billOfProcessIdentification": "https://www.example.com/bop/examplebop",
  "productName": "Barhocker",
  "processSteps": [
    {
      "processStepIdentifier": "Drehen",
      "capabilityReference": "urn:uuid:b5844423-92ac-4527-9b02-bbc64a58d193",
      "childProcessSteps": ["Pick and Place"],
      "inputMaterial": ["Sitzschale, Beine"],
      "outputMaterial": ["Barhocker"],
      "inputParameter": [
        {
          "name": "torque",
          "unit": "Nm",
          "semanticReference": "0173-1#02-AAZ808#001",
          "value": "8",
          "parameterized": "HasValue"
        }
      ],
      "outputParameter": [
        {
          "name": "weight",
          "unit": "kg",
          "semanticReference": "E-Class",
          "value": "2",
          "parameterized": "HasValue"
        }
      ],
      "precedenceRelation": [
        {
          "precedenceElements": [
            {
              "successor": ["Pick and Place"]
            }
          ]
        }
      ]
    },
    {
      "processStepIdentifier": "Pick and Place",
      "capabilityReference": "urn:uuid:a3843423-92ac-4567-1a02-bbc62a56d193",
      "inputMaterial": ["Barhocker"],
      "outputMaterial": ["Barhocker"],
      "inputParameter": [
        {
          "name": "Location",
          "parameterized": "HasNoValue"
        }
      ],
      "outputParameter": [
        {
          "name": "Location",
          "parameterized": "HasNoValue"
        }
      ]
    }
  ]
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by dominikoeh** [comment]
Modeling_Team

**Comment by jacewski-bosch** [comment]
@agg3fe has been assigned as modeling steward.
