### ISSUE TITLE
[Model Update]: io.catenax.parts_analyses:2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by TorstenHirsch** [eclipse-tractusx/sldt-semantic-models#513]
## Update Reason
Use quality decided to put many of the current properties to optional for CX 24.05 release. In addition, some typos in the model example payload and in the description exists.
For model io.catenax.parts_analyses:2.0.0 I assume that some properties are now set to optional - but I don't expect significant change in structure

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists - Catena-X quality use case
- [x] The potential updates are discussed with all stakeholders - discussed in Catena-X use case quality
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [X] The potential update will be either 
  - [X] backward compatible or 
  - [X] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by TorstenHirsch** [comment]
@modelling_team

**Comment by jacewski-bosch** [comment]
@agg3fe has been asigned as modeling steward.
