### ISSUE TITLE
[New Model]: PartClassification 1.0.0

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#520]
## Model Description

This model is used as a shared aspect, that integrates classification properties into the models of the industry core. It provides the possibility for data providers to chose which classification standards for components or parts to use and therefore enables the network to have a broader acceptance towards the various classification standards used in the industry. Moreover, multiple standards can be used for one part these range from E-Class, to ISO, IEC, or STEP. 

The requirement for such an shared aspect was identified due to the Industry Core efforts for harmonization, interoperability, and shall be integrated in all part related aspect models.

## Relevant Standards

https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_PDF_Maerz/8_Semantics/CX_-_0044_ECLASS_v_1.0.1.pdf 

## Example Data

{
  "partClassification": [
    {
      "classificationStandard": "IEC",
      "classificationID": "61360- 2:2012 ",
      "classificationDescription": "Standard data element types with associated classification scheme for electric components "
    }
  ]
}

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by jonbckr** [comment]
modeling_team

**Comment by bosserf** [comment]
The proposed aspect model does not exist already -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> OK
 The proposal references a Catena-X use case -> OK
 Relevant standards are mentioned/linked -> OK
 A first draft of the data structure is provided in an example -> OK
 A modeling steward has been assigned -> @catroest
