### ISSUE TITLE
[New Model]: PackingList 1.0.0

### ISSUE THREAD

**Issue by jonbckr** [eclipse-tractusx/sldt-semantic-models#522]
## Model Description

This new model is part of various aspect models linked to the logistic twin (others e.g. GTL). The PackingList Aspect Model will be a simple representation of a packing list commonly used in logistics. Find an example attached and further information here: https://confluence.catena-x.net/display/BDPQ/DT+transport+UNIT+and+matching+aspect+model+GTL 

![image](https://github.com/eclipse-tractusx/sldt-semantic-models/assets/116578665/b311fbe8-81d0-47eb-a719-3fa7bc6c31de)

## Example Data

{
  "orderNumber": "123456",
  "shippingDate": "2023-02-11",
  "orderDate": "2023-01-12"
  "receiverAddress": {
    "bpnaProperty": "BPNA0123456789ZZ"
  },
  "senderAddress": {
    "bpnaProperty": "BPNA0123456789ZZ"
  },
  "listItems": [
    {
      "itemName": "Valve",
      "quantity": {
        "quantityNumber": 2.5,
        "measurementUnit": "unit:litre"
      },
      "position": 1,
      "itemDescription": "eOMtThyhVNLWUZNRcBaQKxI"
    }
  ],
}

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by jonbckr** [comment]
modeling_team

**Comment by bosserf** [comment]
The proposed aspect model does not exist already -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> OK
 The proposal references a Catena-X use case -> OK
 Relevant standards are mentioned/linked -> OK
 A first draft of the data structure is provided in an example -> OK
 A modeling steward has been assigned -> @agg3fe
