### ISSUE TITLE
[Model Update]: Manufacturing Capability

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sldt-semantic-models#525]
*Resiliency Domain / Manufacturing as a Service*

## Update Reason

The Manufacturing Capability data model is being expanded to include the entities Machine, Tool, and Material, along with their corresponding properties.

https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.manufacturing_capability

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by dominikoeh** [comment]
modeling_team

**Comment by bosserf** [comment]
The model that should be updated exists -> OK
 The referenced use case exists -> OK
 The potential updates are discussed with all stakeholders -> OK
 A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning). -> OK
 The potential update will be either
 backward compatible or
 a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
-> OK (backward compatible)
 A modeling steward has been assigned -> @agg3fe
