### ISSUE TITLE
[New Model]: DaysOfSupply 1.0.0

### ISSUE THREAD

**Issue by zanpi8020** [eclipse-tractusx/sldt-semantic-models#526]
## Model Description
We want to create a model to help with projection and analysis of how much of the item can be manufactured from the current supply at hand.
Days of Supply in logistics is a metric used to estimate how long current inventory levels will last under normal consumption patterns. It is determined by dividing the available inventory by the daily usage rate. This calculation is used in supply chain management and it assists in forecasting when new stock is needed, thereby preventing stock shortages or overstocking. It plays a significant role in ensuring efficient inventory turnover, maintaining a balance between having enough stock to meet demand and avoiding excess inventory that ties up capital. 

## Relevant Standards
There are no relevant standards available, however, this standard will be reusing some of existing elements from other Catena-X standards such as relevant inventory item identifiers.

## Example Data

```json
{
  "daysOfSupply": {
    "inventoryItem": {
      "materialGlobalAssetId": "urn:uuid:12345d48-6f1d-47f5-8ded-a441d0d12345",
      "materialNumberCustomer": "MNR-1234-AU123474.001"
    },
    "currentStockLevel": 150,
    "averageDailyUsage": 50,
    "estimatedDaysOfSupplyRemaining": 3
  }
}
``` 

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by zanpi8020** [comment]
Modeling_Team

**Comment by bosserf** [comment]
The proposed aspect model does not exist already -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> OK
 The proposal references a Catena-X use case -> OK
 Relevant standards are mentioned/linked -> OK
 A first draft of the data structure is provided in an example -> OK
 A modeling steward has been assigned -> @agg3fe
