### ISSUE TITLE
[New Model]: Notifications 1.0.0

### ISSUE THREAD

**Issue by stiwan8020** [eclipse-tractusx/sldt-semantic-models#527]
## Model Description

The Notification model allows the exchange of alerts between business partners. Alerts can occur on site(s) (e.g. strike, earthquake, fire, flood) which can have an effect on another site(s) (demand-reduction, capacity-reduction, capacity-increase, demand-increase). This model also allows to exchange the affected item numbers and a custom user message.

## Relevant Standards

There are no relevant standards available, however, this standard will be reusing some of existing elements from other Catena-X standards such as relevant inventory item identifiers.

## Example Data

I included the "header" in the following example because it has properties which are relevant for the functionality. The actual model example is in the content.
```json
{
    "header": {
        "context": "RES-PURIS-TRACE-DCM-Alert:1.0.0",
        "expectedResponseBy": "2023‐06‐21T21:24:00+07:00",
        "messageId": "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9",
        "relatedMessageId": "d9452f24-3bf3-4134-b3eb-68858f1b2362",
        "recipientBpn": "BPNL6666787765VQ",
        "senderBpn": "BPNL7588787849VQ",
        "sentDateTime": "2023‐06‐19T21:24:00+07:00",
        "version": "urn:samm:io.catenax.message_header:1.0"
    },
    "content": {
        "notifications": [
            {
              "affectedSitesSender": [
                "BPNS7588787849VQ"
              ],
              "affectedSitesReceiver": [
                "BPNS6666787765VQ"
              ], 
              "startDateOfEffect": "2023-12-13T15:00:00+01:00",
              "materialNumberSupplier": [
                "MNR-8101-ID146955.001"
              ],
              "materialNumberCustomer": [
                "MNR-7307-AU340474.002"
              ],
              "materialNumberDigitalTwin": [
                "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
              ],
              "leadingRootCause": "strike",
              "relatedSourceMessageId": "urn:uuid:b3cdDeA6-DC8a-0D7f-dfb5-A6B74bEA2f13",
              "effect": "demand-reduction",
              "text": "HelloWorld",
              "expectedEndDateOfEffect": "2023-12-17T08:00:00+01:00",
              "status": "resolved",
              "contentChangedAt": "2024-01-15T12:32:57.450+01:00",
            }
        ]
    }
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by stiwan8020** [comment]
Modeling_Team

**Comment by bosserf** [comment]
assess the need to integrate the shared message header 
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.shared.message_header

**Comment by stiwan8020** [comment]
need assessed: shared message header will be regulated by the API and won't be included in the aspect model itself.
