### ISSUE TITLE
[New Model]: E-Drive

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#532]
## Model Description
E-Drive passport as a deviation from the Digital Product Passport.
Includes attributes from the transmission.transmission_passport, which will be deprecated in the future.

## Example Data

- DPP general data for metadata of a passport
- Transmission data

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by catroest** [comment]
Modeling_Team

**Comment by bosserf** [comment]
The proposed aspect model does not exist already -> OK
 The proposed aspect model does not extend an existing aspect but introduces completely new functionality -> OK
 The proposal references a Catena-X use case -> OK
 Relevant standards are mentioned/linked -> OK
 A first draft of the data structure is provided in an example -> OK
 A modeling steward has been assigned -> @agg3fe
