### ISSUE TITLE
[New Model]: IoTSensorData

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#54]
## Model Description
Submodel describing the Sensor Data of an IoT Device. 

## Example Data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

Timestamp Sensoric | timestamp |   | 2023-02-04T14:48:54 | XML Schema   (w3.org) |  
-- | -- | -- | -- | -- | --
Latitude | decimal | degree | 4807.03 | ISO 6709 - Wikipedia | GEO Data
Longtitude | decimal | degree | 01131.02 | ISO 6709 - Wikipedia | GEO Data
Altitude | decimal |  meters above mean sea level |  280.2 | http://www.nmea.de/nmea0183datensaetze.html#rmc  | GEO Data
Timestamp Geo data | timestamp |   | 2022-02-04T14:48:54 | XML Schema (w3.org) | GEO Data
Battery Level | decimal | percent | 70 |   |  
Temperature | decimal | degree Celsius | 25 |   |  
Humidity | decimal | percent | 95 |   |  
Light | decimal | lumen | 450 |   |  
Accelaration | decimal | m/s² | 33.528 |   |  
Filling Level | decimal | percent | 45 |   |  
Weight | decimal | kilogram | 15 |   |  
Pressure | decimal | Pascal | 2.6 |   |  

</body>

</html>

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by arnoweiss** [comment]
Maybe check https://reference.opcfoundation.org/DI/v104/docs/ if it might be applicable.
