### ISSUE TITLE
[New Model]: GetProductionTrackingData

### ISSUE THREAD

**Issue by wehrstedt-jan** [eclipse-tractusx/sldt-semantic-models#546]
## Model Description

The Shop Floor Information Service will be extended in 2405 by a method to exchange process data collected during the production of a process for tracebility or documentation. This service will have two actions: a request asking for the data and the answer with the requested data. 

## Relevant Standards

None

This Request corresponds to the GetProductionTrackingData Request:

## Example Data

| Level |  Property | mand./opt. | Semantic ID |
|----|----|----|----|
|CX-Header|"senderBpn"|mandatory|string|
|CX-Header|recipientBpn|mandatory|string|
|CX-Header|context|mandatory|string|
|CX-Header|messageId|mandatory|UUID|
|CX-Header|sentDateTime|mandatory|string|
|CX-Header|version|mandatory|string|
|SIS-Payload|versionDataModel|mandatory|string|
|SIS-Payload|customerId|mandatory|string|
|SIS-Payload|orderId|mandatory|string|
|SIS-Payload|positionId|mandatory|string|
|SIS-Payload|identifierType||[serial, batch, bom]|mandatory |[serial]|[serial]|
|SIS-Payload|identifierNumber|mandatory|string|
|SIS-Payload|processReferenceType||[processStep, capability]|
|SIS-Payload|bopId|0..1|BoP||BoP_ID|
|SIS-Payload|processStepIdentifierList|1|
|SIS-Payload|  capabilityId|(0..n)|
||      partInstanceLevel||[bom, serial]|
||      bomId|1|      BoM|
||      bomElementId|1|      BoM-Element|
||      serialNumber|1|      Seriennummer|
|SIS-Payload|  processStepId|(0..n)|"ProcessStepIdentifier|
|SIS-Payload|     processParameterList|1||
|SIS-Payload|       processParameterName|1..n|"ProcessParameter[string]|
||       processParameterSemanticID|1..n|SemanticID|

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by dominikoeh** [comment]
modeling_team

**Comment by agg3fe** [comment]
Need discussion about using identifier names.
@wehrstedt-jan @jacewski-bosch @jonbckr
