### ISSUE TITLE
[New Model]: IndividualAssetDefinition

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#55]
## Model Description
The Aspect model describes an Individual Asset  individual asset equipped with a bar code/serial number.

## Example Data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

Attribute   Name | Data Type | Unit or Enumeration   values | Data   description | Example | Standard/E-Class   Reference
-- | -- | -- | -- | -- | --
 | | 
CatenaXId | string | Regular   Expression | The fully anonymous Catena-X ID of the asset (serialized Part), valid for the Catena-X dataspace. | urn:uuid:ed85f17e-29dd-473c-9cb8-d7ad1dc44d2f | https://datatracker.ietf.org/doc/html/rfc4122
Asset Owner BPNL | string |   | BPNL   of the asset owner | BPNL021738173000 |  
Serial Number | string |   | The   serial Number of the asset | 321-0740-6790-XY |  
Asset Type | string |   | The   type of the asset |   |  

</body>

</html>

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example

**Comment by bs-jokri** [comment]
check if the model 
https://github.com/admin-shell-io/submodel-templates/tree/main/development/Asset%20Interface%20Description/1/0 
is similar and think about using this one if this is the case

**Comment by sschul33** [comment]
IDTA submodel has been checked by @Cvetanka-ZF but model does not fit to requirements. Also IDTA model is not yet released.

MS1 approved by modelling team.
