### ISSUE TITLE
[New Model]: AssetTrackerLinks

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#56]
## Model Description
The submodel describes the relationship/link between IoT Device and an Individual Asset. 

## Example Data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

Attribute   Name | Data Type | Unit or Enumeration   values | Data   description | Example | Standard/E-Class   Reference
-- | -- | -- | -- | -- | --
| |
catenaXId | string | Regular   Expression | The Catena-X ID of the asset. | urn:uuid:ed85f17e-29dd-473c-9cb8-d7ad1dc44d2f | RFC 4122 - A Universally Unique   IDentifier (UUID) URN Namespace (ietf.org)
childParts | set   / List |   | Encapslation of   all  IoT devices paired/unpaired with   an asset |   |  
childCatenaXId | string | Regular   Expression | The Catena-X ID of the child   object (tracker) which is paied  into   the given parent part (asset). | a67EDBbB-C7c0-a135-7ce6-9E7f47456589 | RFC 4122 - A Universally Unique   IDentifier (UUID) URN Namespace (ietf.org)
paired | boolean |   | currently   paired or not | true, false |  
pairedOn | timestamp |   | timestamp of pairing | 2023-02-03T14:48:54.709Z |  
unpairedOn | timestamp |   | timestamp of unpairing | 2023-02-04T14:48:54.709Z |  

</html>

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by bs-jokri** [comment]
@arnoweiss 
this model represents a concept already available in the AAS meta model but needs to be manually modeled here.

**Comment by arnoweiss** [comment]
Tractus needs a general way to think about modeling Relationships in SAMM. If all SAMM-models are transformed to AAS for deployment anyway, we should find a way to generate the Relationship-SME from a SAMM-structure.

**Comment by Cvetanka-ZF** [comment]
>  Another question for Individual Asset -> is it possible to give a more specific name eg transport container 

Since our product  is called "**Asset Tracking**",  it makes sense to continue using the term "**Individual Asset**".

>Maybe try to not use "relationship" but "link" as this is not as overloaded

Ok. Changed to:  **AssetTrackerLinks**

>Proposal for more specific name for IoTDevice -> LogisticsTrackerDevice

For more specific we can change to :  **IoTSensorDevice**
