### ISSUE TITLE
[Model Update]: Week Based Capacity Group: Adjustment PI 12

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sldt-semantic-models#565]
*Resiliency Domain / Demand and Capacity Management*

> [io.catenax.week_based_capacity_group](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.week_based_capacity_group)

## Update Reason

We would like enhance the week_based_capacity_group model with some parameters to allow the calibration of DCM applications for the measurement of demand volatility.
This metric needs to be calculated in two connected DCM applications in exactly the same way based on the same data.

> Further PI12 topics will be added to this model:
> 
> * Optional inactive flag `isInactive` for capacity group on header level to indicate that this entity is not in use by the supplier anymore:
> 
> ```json
> {
>   "capacityGroupId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
>   .....
>   "isInactive" : true
> }
> ```
> 
>  * New optional property `agreedCapacity` in `capacities` set:
> 
> ```json
> {
>   "capacityGroupId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
>   "capacities" : [ {
>     "pointInTime" : "2022-08-01",
>     "agreedCapacity" : 1800
>     .....
>   } ]
>   .....
> }
> ```

## Sample Data

![image](https://github.com/eclipse-tractusx/sldt-semantic-models/assets/1258026/96d0890c-a73b-4fa7-ba70-b36877dbec7d)

```json
{
  "unitOfMeasureIsOmitted": false,
  "demandVolatilityParameters": {
    "retentionScope": 5,
    "snapshotFrequency": 1,
    "subhorizons": [
      {
        "devRelPos": 1,
        "sequenceNumber": 1,
        "devAbsPos": 100,
        "subHorLength": 1,
        "devRelNeg": 1.5,
        "devAbsNeg": 100
      }
    ],
    "activeFlag": true,
    "snapshotReferenceDateTime": "2024-01-10T12:00:00.320Z"
  },
  "unitOfMeasure": "unit:piece",
  "linkedDemandSeries": [
    {
      "loadFactor": 3.5,
      "materialNumberCustomer": "MNR-7307-AU340474.002",
      "materialNumberSupplier": "MNR-8101-ID146955.001",
      "customerLocation": "BPNS8888888888XX",
      "demandCategory": {
        "demandCategoryCode": "0001"
      }
    }
  ],
  "supplier": "BPNL6666666666YY",
  "linkedCapacityGroups": [
    "be4d8470-2de6-43d2-b5f8-2e5d3eebf3fd"
  ],
  "name": "Spark Plugs on drilling machine for car model XYZ",
  "supplierLocations": [
    "BPNS8888888888XX"
  ],
  "capacities": [
    {
      "pointInTime": "2022-08-01",
      "actualCapacity": 1000,
      "maximumCapacity": 2000,
      "deltaProductionResult": 400
    }
  ],
  "changedAt": "2023-03-10T12:27:11.320Z",
  "capacityGroupId": "0157ba42-d2a8-4e28-8565-7b07830c1110",
  "customer": "BPNL8888888888XX"
}
```

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by nhaenis** [comment]
Further PI12 topics will be added to this model:

- Optional inactive flag `isInactive` for capacity group on header level to indicate that this entity is not in use by the supplier anymore:

```json
{
  "capacityGroupId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
  .....
  "isInactive" : true
}
```

- New optional property `agreedCapacity` in `capacities` set:

```json
{
  "capacityGroupId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
  "capacities" : [ {
    "pointInTime" : "2022-08-01",
    "agreedCapacity" : 1800
    .....
  } ]
  .....
}
```

**Comment by nhaenis** [comment]
@agg3fe will you do the MS2 for this issue and PR #577?

**Comment by agg3fe** [comment]
> @agg3fe will you do the MS2 for this issue and PR #577?

Issue does not need any further approval. For PR, I will do the MS2 approval.
