### ISSUE TITLE
[Model Update]: PartAsPlanned 3.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#566]
## Update Reason
Based on the continous development of the Industry Core, there are a new data, that needs to be integrated in the **PartAsPlanned** aspect model:

- Integration of the new shared Classifcation model (#520)
- Permit to add date information excluding time 
``` 
^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2}))?$
``` 

## Relevant Standards
- CX-0126 Industry Core: Part Type 2.0.0 (if merged before 29.02.24)

## Example Data
```json
{
  "catenaXId": "580d3adf-1981-44a0-a214-13d6ceed9379",
  "partTypeInformation": {
    "manufacturerPartId": "123-0.740-3434-A",
    "nameAtManufacturer": "Mirror left",
    "partClassification": [
      {
        "classificationStandard": "IEC",
        "classificationID": "61360- 2:2012 ",
        "classificationDescription": "Standard data element types with associated classification scheme for electric components."
      }
    ]
  },
  "partSitesInformationAsPlanned": [
    {
      "functionValidUntil": "0558-65-61T42:39:64+69:77",
      "catenaXsiteId": "BPNS1234567890ZZ",
      "function": "production",
      "functionValidFrom": "8343-44-37T24:99:37.51527Z"
    }
  ]
}
```

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by johannsvarela** [comment]
@agg3fe @catroest Since we want to rename the PartAsPlanned aspect model, this issue can be closed / set deprecate and therefore will be replaced by a new issue: **[New Model]: PartTypeInformation 1.0.0 #591**

@tomaszbarwicki @jonbckr @BenediktMuellerIML FYI

**Comment by agg3fe** [comment]
@johannsvarela should I close this issue and PR #567 , both?

**Comment by johannsvarela** [comment]
> @johannsvarela should I close this issue and PR #567 , both?

Yes! :)

**Comment by agg3fe** [comment]
closing as renaming would be required for the model.
Since we want to rename the PartAsPlanned aspect model, this issue can be closed / set deprecate and therefore will be replaced by a new issue: [New Model]: PartTypeInformation 1.0.0 https://github.com/eclipse-tractusx/sldt-semantic-models/issues/591
