### ISSUE TITLE
[Model Issue]: QualityTaskAttachment incorrect example value

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sldt-semantic-models#598]
## Issue Description

Example value for [QualityTaskAttachment](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.quality_task_attachment/1.0.0) model  property 'unit' is not correct. 
current value: degreeCelsiusPerHour
correct value: unit:degreeCelsiusPerHour"^^samm:curie

**Comment by agg3fe** [comment]
@JulianSchererZF Could you please check this request. The example value needs to be corrected in model. I have specified the correct value also. 
New version of the model would be required.

**Comment by JulianSchererZF** [comment]
@agg3fe, I will have a look into it ASAP

**Comment by JulianSchererZF** [comment]
> @JulianSchererZF Could you please check this request. The example value needs to be corrected in model. I have specified the correct value also. New version of the model would be required.

@agg3fe I modified the model as you mentioned. Do we need a Version 2.0.0 here or would be a version 1.0.1 possible?

**Comment by agg3fe** [comment]
> > @JulianSchererZF Could you please check this request. The example value needs to be corrected in model. I have specified the correct value also. New version of the model would be required.
> 
> @agg3fe I modified the model as you mentioned. Do we need a Version 2.0.0 here or would be a version 1.0.1 possible?

Version 2.0.0 would be required as this is major change from bamm to samm also.

**Comment by JulianSchererZF** [comment]
> > > @JulianSchererZF Could you please check this request. The example value needs to be corrected in model. I have specified the correct value also. New version of the model would be required.
> > 
> > 
> > @agg3fe I modified the model as you mentioned. Do we need a Version 2.0.0 here or would be a version 1.0.1 possible?
> 
> Version 2.0.0 would be required as this is major change from bamm to samm also.

It was already modeled in SAMM so it would be only the wrong example value what has changed

**Comment by agg3fe** [comment]
> > > > @JulianSchererZF Could you please check this request. The example value needs to be corrected in model. I have specified the correct value also. New version of the model would be required.
> > > 
> > > 
> > > @agg3fe I modified the model as you mentioned. Do we need a Version 2.0.0 here or would be a version 1.0.1 possible?
> > 
> > 
> > Version 2.0.0 would be required as this is major change from bamm to samm also.
> 
> It was already modeled in SAMM so it would be only the wrong example value what has changed

Yes. still it would need major version as samm migration will be there from 2.0.0 to 2.1.0
