### ISSUE TITLE
[Model Update]: Refurbishing_Certificate v2.1.0

### ISSUE THREAD

**Issue by SophieOdette** [eclipse-tractusx/sldt-semantic-models#615]
add attributes: revocation Date, serial number

link to the current version of the Refurbishing_Certificate (v2.0.0):
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.refurbishing_certificate/2.0.0/RefurbishingCertificate.ttl

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by SophieOdette** [comment]
Modeling_Team

**Comment by agg3fe** [comment]
major version change required
