### ISSUE TITLE
[Model Update]: SingleLevelUsageAsPlanned 2.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#633]
## Update Reason
Based on continuous development of the Industry Core, the ability to **run up the data chain** for PartType twins was implemented so that the relationship described by the **SingleLevelUsageAsPlanned** model meets the requirements of the data chain template. 

## Relevant Standard
CX-0126 Industry Core: Part Type

## Example Data
```json
{
  "catenaXId": "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
  "parentItems": [
    {
      "validityPeriod": {
        "validFrom": "2023-03-21T08:17:29.187+01:00",
        "validTo": "2024-07-01T16:10:00.000+01:00"
      },
      "parentCatenaXId": "urn:uuid:43364d8c-cf38-423c-b907-6e68e0f0fe2f",
      "isOnlyPotentialParent": true,
      "quantity": {
        "quantityValue": 20,
        "itemUnit": "unit:piece"
      },
      "businessPartner": "BPNL50096894aNXY",
      "createdOn": "2022-02-03T14:48:54.709Z",
      "lastModifiedOn": "2022-02-03T14:48:54.709Z"
    }
  ],
  "customers": [
    {
      "createdOn": "2022-02-03T14:48:54.709Z",
      "businessPartner": "BPNL50096894aNXY",
      "lastModifiedOn": "2022-02-03T14:48:54.709Z"
    }
  ]
}
```

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by johannsvarela** [comment]
modeling_team

**Comment by johannsvarela** [comment]
FYI @jacewski-bosch @BenediktMuellerIML

**Comment by agg3fe** [comment]
#549
