### ISSUE TITLE
[New Model]: Shared Aspect for Demand Category

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sldt-semantic-models#664]
## Model Description

During model update of demand (#545), we decided that it might be smart to create an own model. Thus, we want to extract reuseable stuff from the demand model.

## Example Data

```
{
  "demandCategory" : {
    "demandCategoryCode" : "0001"
  }
}
```

## MS1 Criteria

- [ ] The proposed aspect model does not exist already
- [ ] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [ ] The proposal references a Catena-X use case
- [ ] Relevant standards are mentioned/linked
- [ ] A first draft of the data structure is provided in an example
- [ ] A modeling steward has been assigned

**Comment by agg3fe** [comment]
Discussion required.

**Comment by tom-rm-meyer-ISST** [comment]
Due to time constraints, there won't be a shared aspect model
