### ISSUE TITLE
[Model Update]: DaysOfSupply 2.0.0

### ISSUE THREAD

**Issue by stiwan8020** [eclipse-tractusx/sldt-semantic-models#676]
## Update Reason

Days of Supply in logistics is a metric used to estimate how long current inventory levels will last under normal consumption patterns. Days of Supply metric is used in supply chain management and it assists in forecasting when new stock is needed, thereby preventing stock shortages or overstocking. It plays a significant role in ensuring efficient inventory turnover, maintaining a balance between having enough stock to meet demand and avoiding excess inventory that ties up capital.
 
**In the revised version we added lastUpdatedOnDateTime property which describes the date of the according data object update, to ensure clarity and compatibility with other models.**

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [x] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [x] A modeling steward has been assigned

**Comment by zanpi8020** [comment]
Modeling_Team
