### ISSUE TITLE
[Model Update]:  SingleLevelBomAsPlanned include versions and validity

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-tractusx/sldt-semantic-models#73]
## Update Reason
We need to update this Aspect to include all Part versions and validity (asPlanned) to cover versioning of components and vehicles

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by jacewski-bosch** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
similar to #74 same comments apply

**Comment by jacewski-bosch** [comment]
closed with #123
