### ISSUE TITLE
[Model Update]:  SingleLevelUsageAsPlanned include versions and validity

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-tractusx/sldt-semantic-models#74]
## Update Reason
We need to update this Aspect to include all Part versions and validity (asPlanned) to cover the versioning of components and vehicles. As in #73 

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by jacewski-bosch** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
original model needs to be merged from fork

**Comment by bs-jokri** [comment]
Version will be explicitly mention in description. for Validity period new optional properties need be introduced.
Will be backwards compatible.
