### ISSUE TITLE
[Model Update]: Renaming of AssemblyPartRelationship and SerialPartTypization 

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-tractusx/sldt-semantic-models#75]
## Update Reason
We want to rename the latest released version of AssemblyPartRelationship and SerialPartTypization to match our naming convention from BoMAsPlanned and other BoMs.

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by jacewski-bosch** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
from discussion: renaming will take place in two steps: first step: deprecating the old model. Second step, create new model. But, it is important to a also have a migration plan at hand. 
Two new tickets
AssemblyPartRelationship will become SingleLevelBomAsBuilt
SerialPartTypization, the new name needs to be discussed

**Comment by bs-jokri** [comment]
new tickets
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/78
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/79
