### ISSUE TITLE
[Model Deprecation]: AssemblyPartRelationship (to be replaced by SingleLevelBomAsBuilt)

### ISSUE THREAD

**Issue by BenediktMuellerIML** [eclipse-tractusx/sldt-semantic-models#76]
## Update Reason
AssemblyPartRelationship should be deprecated to be replaced by new model SingleLevelBomAsBuilt to match our naming convention from BomAsPlanned and other BoMs. 

## MS1 Criteria

- [x] The model that should be deprecated exists and is not deprecated already
- [x] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [x] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by bs-jokri** [comment]
as discussed #75 models will be deprecated.
