### ISSUE TITLE
[New Model]: CustomsInformation 1.0.0

### ISSUE THREAD

**Issue by johannsvarela** [eclipse-tractusx/sldt-semantic-models#763]
## Model Description
To carry out a preference calculation, customs-specific master data is required for all installed parts within a product. For this purpose, the manufacturer of the product requests this information from the relevant suppliers for all purchased parts (part numbers) and uses it for the preference calculation.

The exchange takes place peer-to-peer from one value-added participant across the two tier levels. 

## Relevant Standards
Possibly CX-0125 Traceability Use Case (next version)

## Example Data
```json
{
  "catenaXId": "580d3adf-1981-44a0-a214-13d6ceed9379",
  "customsInformation": [
    {
      "confirmationDate": "2024-03-27",
      "validFrom": "2024-03-20",
      "type": "AnnualRequest",
      "originInformation": {
        "tradeRelation": "EU-MX",
        "tracedWorth": {
          "value": 300.45,
          "currency": "EUR"
        },
        "preferedStatus": "Y-Certified",
        "contactInformation": {
          "contactPerson": "Max Mustermann",
          "phoneNumber": "+49 89 123456",
          "email": "max.mustermann@ziel.de",
          "jobTitle": "executive position"
        },
        "commercialCountryOfOrigin": "DE",
        "originOfManufacturing": {
          "longitude": 13.214907205727538,
          "latitude": 59.351212217399095
        },
        "federalState": "BW"
      },
      "status": "Commited"
    }
  ]
}
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example
- [x] A modeling steward has been assigned

**Comment by johannsvarela** [comment]
modeling_team

**Comment by jSchuetz88** [comment]
Looks good to me, MS1 approved.
