### ISSUE TITLE
[PROCESS]: README file: Version of Aspect Model Editor and SAMM-CLI correct?

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-tractusx/sldt-semantic-models#769]
In
https://github.com/eclipse-tractusx/sldt-semantic-models?tab=readme-ov-file
it is mentioned that version 5.1.1 of the asepct model editor shall be used. The link is not valid any longer: there is a version 5.6.0: https://eclipse-esmf.github.io/ame-guide/5.6.0/introduction.html
is it really a must to use this old version of the aspect model editor?

is it really version 2.6.0 of the [SAMM-CLI](https://eclipse-esmf.github.io/esmf-developer-guide/2.6.0/tooling-guide/samm-cli.html) in all cases, at least for aasx generation there were some bugfixes that should be considered.

**Comment by agg3fe** [comment]
Hi @BirgitBoss , Here's the PR considering the changes https://github.com/eclipse-tractusx/sldt-semantic-models/pull/766.
We will do few validation tests before merging it.
