### ISSUE TITLE
[Model Deprecation]: SerialPartTypization (to be replaced by SerialPartAsBuilt)

### ISSUE THREAD

**Issue by BenediktMuellerIML** [eclipse-tractusx/sldt-semantic-models#77]
## Update Reason
SerialPartTypization should be deprecated to be replaced by SerialPartAsBuilt to match our naming convention from BomAsPlanned and other BoMs.

## MS1 Criteria

- [x] The model that should be deprecated exists and is not deprecated already
- [x] The respective model does not affect existing use cases (aspect is either used in higher versions or replaced by a different aspect)
- [ ] A shared aspect, which will be deprecated, is not used by any released aspect model

**Comment by BenediktMuellerIML** [comment]
Modeling_Team
Model_Update

**Comment by bs-jokri** [comment]
Transmission, Sealant Models use parts of this model. They will be updated with the next version.
