### ISSUE TITLE
[Model Update]: update business_partner_certificate

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/sldt-semantic-models#771]
## Update Reason

The `enclosedSiteBpn` property is updated to accept both business partner number of type site (bpns) and business partner number of type addresses (bpna) to better manage certificates for multiple sites. Additionally, the Validator object is made optional, including `validatorName` and `validatorBpn`, for increased flexibility in validation details.

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [ ] A modeling steward has been assigned

**Comment by SujitMBRDI** [comment]
FYI: @jSchuetz88, @agg3fe , modeling_team

**Comment by jSchuetz88** [comment]
Hi @SujitMBRDI,

the updated model looks good to me. In my understanding, the updated version should technically be backward compatible?

**Comment by SujitMBRDI** [comment]
> Hi @SujitMBRDI,
> 
> the updated model looks good to me. In my understanding, the updated version should technically be backward compatible?

Hi @jSchuetz88,
Thank you for reviewing changes and for providing MS1 approval.
And yes, changes are backward compatible with no breaking change.
