### ISSUE TITLE
[Model Update]: WeekBasedCapacityGroup v.3.0.0.

### ISSUE THREAD

**Issue by LukasSchmetz** [eclipse-tractusx/sldt-semantic-models#774]
## Update Reason
A few descriptions in the WeekBasedCapacity Group v.3.0.0 Data Model are currently wrong and need to be fixed.

## MS1 Criteria
This checklist is filled by the issue reviewer
- [x] The model that should be updated exists => __WeekBasedCapacityGroup v.3.0.0__
- [x] The referenced use case exists => __Demand and Capacity Management (DCM)__
- [x] The potential updates are discussed with all stakeholders => __Errors detected during DCM KIT Updates for R.24.12__
- [x] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning). => __Patch Update to Version 3.0.1__
- [x] The potential update will be either 
  - [x] backward compatible
- [x] A modeling steward has been assigned __@jSchuetz88__

**Comment by jSchuetz88** [comment]
As the corresponding PR has been merged, I close this issue.
