### ISSUE TITLE
Adapt action to be executed only if there is a ttl file involved

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sldt-semantic-models#786]
## Description

Currently, the action [generates models](https://github.com/eclipse-tractusx/sldt-semantic-models/actions/runs/11774835101/job/32794117391) fails, if there is no TTL file in the commit.

=> his should be avoided

## Expected behaviour

If there is no TTL file included in the commit, the check shouldn't be executed.

**Comment by jSchuetz88** [comment]
Should be done, see PR #788
