### ISSUE TITLE
[New Model]: [Traceability] New model SerialPartAsBuilt (replacement of SerialPartTypization)

### ISSUE THREAD

**Issue by BenediktMuellerIML** [eclipse-tractusx/sldt-semantic-models#79]
## Model Description
We want to create a new model named SerialPartAsBuilt which will replace the existing model SerialPartTypization. The reason for the replacement is to match our naming convention from BomAsPlanned and other BoMs. 

## Relevant Standards
New model will replace existing SerialPartTypization therefore not appicable

## Example Data
New model will replace existing SerialPartTypization, therefore not appicable

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by BenediktMuellerIML** [comment]
Modeling_Team
Model_Update

**Comment by bs-jokri** [comment]
old model will be deprecated if this model is released
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/77

**Comment by bs-jokri** [comment]
The exact name will be defined in the modeling process

**Comment by jacewski-bosch** [comment]
new name proposal is SerialPart
