### ISSUE TITLE
[Model Update]: Business Partner Certificate v. 2.0.0

### ISSUE THREAD

**Issue by Cvetanka-ZF** [eclipse-tractusx/sldt-semantic-models#791]
## Update Reason
The current model is inadequate for a decentralised architecture. 

1. The model should be extended to include data attributes for the physical document.  
          ex. 
                  "document": {
                                              "documentID": "UUID--123456789",
                                              "creationDate": "2024-08-23T13:19:00.280+02:00",
                                              "contentType": "application/pdf",
                                              "contentBase64": "iVBORw0KGgoAAdsfwerTETEfdgd"
                                     }

2.  The data attribute issurer (which is currently optional and represents a BPN) should be extended to include the name of the issurer as a mandatory attribute. 
         ex.   
                     "issuer": {
                                             "issuerBpn": "BPNL13363112312",
                                             "issuerName": "TÜV"
                                      }

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed
- [ ] A modeling steward has been assigned

**Comment by maximilianong** [comment]
We discussed this topic in the company certificate expert group and agree to the changes!
Thanks @Cvetanka-ZF for brining this up and doing the changes.

**Comment by jcjollant** [comment]
Thanks for the prompt turnaround
