### ISSUE TITLE
[Model Update]: Address wrong description

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sldt-semantic-models#80]
## Update Reason

Fehlerhafte Beschreibung und prefered name:

:LocalityEntity a bamm:Entity;
    bamm:name "LocalityEntity";
    bamm:preferredName **"Thoroughfare Entity"**@en;
    bamm:description "**Entity for a thoroughfare which consists of a type, value and number.**"@en;

## MS1 Criteria

- [x] The model that should be updated exists
- [x] The referenced use case exists
- [x] The potential updates are discussed with all stakeholders
- [x] The potential update will be either 
  - [x] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by catroest** [comment]
@bs-jokri Model kam von dir? Hier ist eine Beschreibung und preferred name kopiert und nicht geändert worden.

**Comment by catroest** [comment]
Modeling_Team

**Comment by ZazraltMagic** [comment]
- [ok] exists (shared address)
- [ok] for anyone (shared)
- [ok] patch update
- [ok] backward compatible

M1 approved
@bs-jokri

**Comment by bs-jokri** [comment]
@catroest don't forget to adjust model version with the update. Assume a minor update.
