### ISSUE TITLE
Upload Models to an instance of the Semantic Hub

### ISSUE THREAD

**Issue by eriksven** [eclipse-tractusx/sldt-semantic-models#9]
In https://github.com/eclipse-tractusx/sldt-semantic-hub we develop the Semantic Hub which manages and processes semantic models based on BAMM. It would be beneficial to have an GitHub action which uploads the semantic models which are proposed to this sldt-semantic-models repository to an instance of the Semantic Hub. This way the models get validated and can be visualized or consumed from there.

**Comment by bs-jokri** [comment]
check PR 
https://github.com/eclipse-tractusx/sldt-semantic-models/pull/16
which resolves this issue
