### ISSUE TITLE
[New Model]: Time Series

### ISSUE THREAD

**Issue by TobiasHamacherDLR** [eclipse-tractusx/sldt-semantic-models#94]
## Model Description
For running time dependent simulations, time dependent input data in human readable format is required by the software tools. For some applications using measurement data, the data might also be provided in human readable format. In order to make the processing of the data easier for the tool used, we want to standardize how time series (in human readable format) should be exchanged.  

## Relevant Standards
An AAS Model for “Time Series Data” is currently in development https://industrialdigitaltwin.org/content-hub/teilmodelle. Other standards exist like MDF4 generally used for measurement data. However this is a binary file (not human readable). Important CSV (comma separated value format) is not a standard

## Example Data
Time	V	RPM	Torque	aZ
s	km/h	rpm	Nm	m/s^2
0.00	6.18E-01	3.85E-01	2.35E-01	6.59E-01
0.50	9.31E-01	3.82E-01	9.84E-01	2.18E-01
1.00	4.28E-01	4.32E-01	3.71E-01	4.49E-01
1.50	1.03E-02	2.98E-01	1.30E-01	9.47E-01
2.00	9.20E-01	3.71E-01	1.64E-01	6.44E-01
2.50	8.44E-01	5.55E-01	4.63E-01	2.10E-01
3.00	5.19E-01	5.97E-01	5.07E-01	1.78E-01
3.50	5.69E-01	9.81E-01	6.40E-01	2.92E-01
4.00	7.98E-01	7.83E-02	2.02E-01	8.32E-01
4.50	6.69E-01	5.74E-01	6.60E-01	8.56E-01
5.00	6.20E-01	6.08E-01	7.82E-02	7.93E-01
5.50	2.87E-01	5.58E-01	8.57E-01	6.46E-01
6.00	3.26E-01	5.30E-01	3.75E-01	5.26E-01
6.50	6.43E-01	6.68E-02	2.21E-01	3.40E-01
7.00	6.42E-01	2.72E-01	9.26E-01	2.91E-01
7.50	8.21E-01	7.03E-01	9.45E-02	4.74E-01
8.00	2.36E-01	8.27E-01	3.58E-02	3.02E-01
8.50	7.31E-01	6.82E-01	6.60E-01	2.29E-01
9.00	8.43E-01	9.51E-01	5.17E-02	5.07E-01
9.50	8.54E-01	1.29E-01	3.78E-02	9.04E-01
10.00	1.03E-01	1.76E-01	4.24E-01	1.63E-01

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

**Comment by TobiasHamacherDLR** [comment]
Modeling_Team

**Comment by bs-jokri** [comment]
From discussion: given example model is an example. The given column names are only examples and can be replaced with arbitrary other columns.
Time stamps for each row is given
